/**
 * Travelog MVP1 — Manual trip creation integration tests
 *
 * Manual trip creation when photos have no GPS EXIF (user request):
 * trip built day by day, each with localities resolved through the
 * autocomplete flow; day replacement on existing trips; split/merge
 * copy the manual days to the resulting trips. Uses the real
 * PostgreSQL test database (travelog_test).
 */

import { describe, it, expect, beforeEach, afterAll } from "vitest";
import request from "supertest";
import { pool } from "../db/client.js";
import { createApp } from "../app.js";

const server = createApp();

// ── Fixtures ─────────────────────────────────────────────────

async function insertLocality(name: string): Promise<number> {
  const res = await pool.query(
    `INSERT INTO localities (locality_hash, country_code, name, admin_level, county, region, country)
     VALUES ($1, 'IT', $2, 8, 'Test County', 'Test Region', 'Italy') RETURNING id`,
    [`manual-test-${name.toLowerCase()}`, name],
  );
  return Number(res.rows[0].id);
}

async function insertTrip(name: string, startDate: string, endDate: string): Promise<number> {
  const res = await pool.query(
    `INSERT INTO trips (name, start_date, end_date, auto_generated, status)
     VALUES ($1, $2::date, $3::date, true, 'active') RETURNING id`,
    [name, startDate, endDate],
  );
  return Number(res.rows[0].id);
}

async function manualDayRows(tripId: number): Promise<Array<{ day: string; locality: string }>> {
  const res = await pool.query(
    `SELECT to_char(d.day_date, 'YYYY-MM-DD') AS day, l.name AS locality
     FROM manual_trip_days d
     LEFT JOIN manual_trip_day_localities m ON m.day_id = d.id
     LEFT JOIN localities l ON l.id = m.locality_id
     WHERE d.trip_id = $1::int AND l.id IS NOT NULL
     ORDER BY d.day_date, l.name`,
    [tripId],
  );
  return res.rows.map((r) => ({ day: String(r.day), locality: String(r.locality) }));
}

async function manualDayCount(tripId: number): Promise<number> {
  const res = await pool.query(
    `SELECT count(*) AS n FROM manual_trip_days WHERE trip_id = $1::int`,
    [tripId],
  );
  return Number(res.rows[0].n);
}

// ── Cleanup ──────────────────────────────────────────────────

async function cleanup() {
  await pool.query(
    "TRUNCATE trips, trip_history, manual_trip_days, manual_trip_day_localities RESTART IDENTITY",
  );
  await pool.query("TRUNCATE presences RESTART IDENTITY");
  await pool.query("DELETE FROM localities WHERE locality_hash LIKE 'manual-test-%'");
}

beforeEach(async () => {
  await cleanup();
});

afterAll(async () => {
  await cleanup();
  await pool.end();
});

// ── Tests ────────────────────────────────────────────────────

describe("manual trip creation with days", () => {
  it("creates a trip from manual days and derives the interval", async () => {
    const erice = await insertLocality("Erice");
    const milano = await insertLocality("Milano");
    const res = await request(server)
      .post("/api/trips")
      .send({
        name: "Sicilia",
        days: [
          { date: "2025-08-12", localityIds: [milano] },
          { date: "2025-08-10", localityIds: [erice] },
          { date: "2025-08-11", localityIds: [erice] },
        ],
      });
    expect(res.status).toBe(201);
    expect(res.body.name).toBe("Sicilia");
    expect(res.body.startDate).toBe("2025-08-10");
    expect(res.body.endDate).toBe("2025-08-12");
    expect(res.body.autoGenerated).toBe(false);
    // Manual-creation provenance: only POST /trips marks a trip as manual.
    expect(res.body.createdManually).toBe(true);

    const detail = await request(server).get(`/api/trips/${res.body.id}`);
    expect(detail.status).toBe(200);
    const days = detail.body.days as Array<{
      date: string;
      noPhotos: boolean;
      localities: Array<{ name: string; photoCount: number; manual: boolean }>;
    }>;
    expect(days.map((d) => d.date)).toEqual(["2025-08-10", "2025-08-11", "2025-08-12"]);
    expect(days[0].localities[0]).toMatchObject({ name: "Erice", photoCount: 0, manual: true });
  });

  it("deduplicates (date, locality) pairs", async () => {
    const erice = await insertLocality("Erice");
    const res = await request(server)
      .post("/api/trips")
      .send({
        days: [
          { date: "2025-08-10", localityIds: [erice] },
          { date: "2025-08-10", localityIds: [erice] },
        ],
      });
    expect(res.status).toBe(201);
    expect(await manualDayRows(res.body.id)).toEqual([{ day: "2025-08-10", locality: "Erice" }]);
  });

  it("rejects unknown localities", async () => {
    const res = await request(server)
      .post("/api/trips")
      .send({ days: [{ date: "2025-08-10", localityIds: [999999] }] });
    expect(res.status).toBe(400);
  });

  it("blocks overlap with another active trip (§21.17)", async () => {
    await insertTrip("Esistente", "2025-08-08", "2025-08-11");
    const erice = await insertLocality("Erice");
    const res = await request(server)
      .post("/api/trips")
      .send({ days: [{ date: "2025-08-10", localityIds: [erice] }] });
    expect(res.status).toBe(409);
    expect(res.body.code).toBe("TRIP_OVERLAP");
  });

  it("creates a day without localities and completes it later (workflow)", async () => {
    const erice = await insertLocality("Erice");
    // Step 3–4 of the workflow: the day is added before its localities.
    const created = await request(server)
      .post("/api/trips")
      .send({ name: "W", days: [{ date: "2025-08-10" }] });
    expect(created.status).toBe(201);

    const detail = await request(server).get(`/api/trips/${created.body.id}`);
    expect(detail.status).toBe(200);
    expect(detail.body.days).toHaveLength(1);
    expect(detail.body.days[0]).toMatchObject({
      date: "2025-08-10",
      noPhotos: false,
      manual: true,
    });
    expect(detail.body.days[0].localities).toEqual([]);

    // Step 5–6: the locality is added to the day via day replacement.
    const completed = await request(server)
      .put(`/api/trips/${created.body.id}/days`)
      .send({ days: [{ date: "2025-08-10", localityIds: [erice] }] });
    expect(completed.status).toBe(200);
    expect(completed.body.days[0].localities).toHaveLength(1);
    expect(completed.body.days[0].localities[0]).toMatchObject({
      name: "Erice",
      manual: true,
      photoCount: 0,
    });
    expect(await manualDayCount(created.body.id)).toBe(1);
  });
});

describe("manual day replacement (PUT /trips/:id/days)", () => {
  it("adds a day beyond the trip end by extending the dates", async () => {
    const erice = await insertLocality("Erice");
    const milano = await insertLocality("Milano");
    const created = await request(server)
      .post("/api/trips")
      .send({ name: "T", days: [{ date: "2025-08-10", localityIds: [erice] }] });
    const tripId = created.body.id as number;

    const res = await request(server)
      .put(`/api/trips/${tripId}/days`)
      .send({
        days: [
          { date: "2025-08-10", localityIds: [erice] },
          { date: "2025-08-12", localityIds: [milano] },
        ],
      });
    expect(res.status).toBe(200);
    expect(res.body.startDate).toBe("2025-08-10");
    expect(res.body.endDate).toBe("2025-08-12");
    expect(await manualDayRows(tripId)).toEqual([
      { day: "2025-08-10", locality: "Erice" },
      { day: "2025-08-12", locality: "Milano" },
    ]);
  });

  it("refuses to empty the day list and blocks archived trips", async () => {
    const erice = await insertLocality("Erice");
    const created = await request(server)
      .post("/api/trips")
      .send({ name: "T", days: [{ date: "2025-08-10", localityIds: [erice] }] });
    const tripId = created.body.id as number;
    const empty = await request(server).put(`/api/trips/${tripId}/days`).send({ days: [] });
    expect(empty.status).toBe(400);

    await pool.query(`UPDATE trips SET status = 'archived' WHERE id = $1::int`, [tripId]);
    const archived = await request(server)
      .put(`/api/trips/${tripId}/days`)
      .send({ days: [{ date: "2025-08-10", localityIds: [erice] }] });
    expect(archived.status).toBe(409);
    expect(archived.body.code).toBe("TRIP_NOT_ACTIVE");
  });

  it("removes manual days falling outside a shortened date range", async () => {
    const erice = await insertLocality("Erice");
    const milano = await insertLocality("Milano");
    const created = await request(server)
      .post("/api/trips")
      .send({
        name: "T",
        days: [
          { date: "2025-08-10", localityIds: [erice] },
          { date: "2025-08-14", localityIds: [milano] },
        ],
      });
    const tripId = created.body.id as number;
    const res = await request(server)
      .patch(`/api/trips/${tripId}`)
      .send({ startDate: "2025-08-12", endDate: "2025-08-14" });
    expect(res.status).toBe(200);
    expect(await manualDayRows(tripId)).toEqual([{ day: "2025-08-14", locality: "Milano" }]);
  });
});

describe("split and merge copy the manual days", () => {
  it("split assigns the days by date (the split date belongs to the second trip)", async () => {
    const erice = await insertLocality("Erice");
    const milano = await insertLocality("Milano");
    const created = await request(server)
      .post("/api/trips")
      .send({
        name: "Origine",
        days: [
          { date: "2025-08-10", localityIds: [erice] },
          { date: "2025-08-11", localityIds: [milano] },
          { date: "2025-08-12", localityIds: [milano] },
        ],
      });
    const tripId = created.body.id as number;
    const res = await request(server)
      .post(`/api/trips/${tripId}/split`)
      .send({ splitDate: "2025-08-11" });
    expect(res.status).toBe(200);
    const [first, second] = res.body.trips;
    expect(first.startDate).toBe("2025-08-10");
    expect(await manualDayRows(first.id)).toEqual([{ day: "2025-08-10", locality: "Erice" }]);
    expect(await manualDayRows(second.id)).toEqual([
      { day: "2025-08-11", locality: "Milano" },
      { day: "2025-08-12", locality: "Milano" },
    ]);
    // The archived original keeps its own rows for the audit history.
    expect(await manualDayRows(tripId)).toHaveLength(3);
  });

  it("merge copies all manual days without duplicating shared pairs", async () => {
    const erice = await insertLocality("Erice");
    const milano = await insertLocality("Milano");
    const a = await request(server)
      .post("/api/trips")
      .send({ name: "A", days: [{ date: "2025-08-10", localityIds: [erice] }] });
    const b = await request(server)
      .post("/api/trips")
      .send({ name: "B", days: [{ date: "2025-08-13", localityIds: [milano] }] });
    const res = await request(server)
      .post("/api/trips/merge")
      .send({ tripIds: [a.body.id, b.body.id] });
    expect(res.status).toBe(200);
    const merged = res.body.trips[0];
    expect(merged.startDate).toBe("2025-08-10");
    expect(merged.endDate).toBe("2025-08-13");
    // Manual provenance: at least one merged trip is manual.
    expect(merged.createdManually).toBe(true);
    expect(await manualDayRows(merged.id)).toEqual([
      { day: "2025-08-10", locality: "Erice" },
      { day: "2025-08-13", locality: "Milano" },
    ]);
  });

  it("merge of auto-generated trips is not marked as manually created", async () => {
    const a = await insertTrip("A", "2025-08-10", "2025-08-11");
    const b = await insertTrip("B", "2025-08-13", "2025-08-14");
    const res = await request(server)
      .post("/api/trips/merge")
      .send({ tripIds: [a, b] });
    expect(res.status).toBe(200);
    expect(res.body.trips[0].createdManually).toBe(false);
  });
});
