/**
 * Travelog MVP1 — Trip ICS export integration test
 *
 * Uses the real PostgreSQL test database (travelog_test) and verifies
 * the GET /trips/:tripId/ics endpoint end-to-end: content type,
 * attachment header, VCALENDAR structure, all-day event with exclusive
 * DTEND, LOCATION (top locality by photo count) and DESCRIPTION with
 * the hierarchy plus the "Creato da Travelog" signature.
 */

import { describe, it, expect, beforeEach, afterAll } from "vitest";
import request from "supertest";
import { pool } from "../db/client.js";
import { createApp } from "../app.js";

const server = createApp();

async function insertTrip(
  name: string,
  startDate: string,
  endDate: string,
  opts: { autoGenerated?: boolean; status?: string } = {},
): Promise<number> {
  const res = await pool.query(
    `INSERT INTO trips (name, start_date, end_date, auto_generated, status)
     VALUES ($1, $2::date, $3::date, $4, $5) RETURNING id`,
    [name, startDate, endDate, opts.autoGenerated ?? true, opts.status ?? "active"],
  );
  return Number(res.rows[0].id);
}

async function cleanup() {
  await pool.query("DELETE FROM photos WHERE file_path LIKE 'ics-test/%'");
  await pool.query("TRUNCATE presences RESTART IDENTITY");
  await pool.query(
    "TRUNCATE trips, trip_history, manual_trip_days, manual_trip_day_localities, trip_day_exclusions RESTART IDENTITY",
  );
  await pool.query("DELETE FROM geocoding_cache WHERE locality_hash LIKE 'ics-test-%'");
  await pool.query("DELETE FROM localities WHERE locality_hash LIKE 'ics-test-%'");
}

beforeEach(async () => {
  await cleanup();
});

afterAll(async () => {
  await cleanup();
  await pool.end();
});

describe("GET /api/trips/:tripId/ics (ICS)", () => {
  it("returns a text/calendar attachment with the trip as an all-day event", async () => {
    const tripId = await insertTrip("Sicilia", "2025-08-10", "2025-08-24");

    // Insert two localities: Erice (4 photos total) and Milano (2 photos).
    const erice = await pool.query(
      `INSERT INTO localities (locality_hash, country_code, name, admin_level, county, region, country)
       VALUES ('ics-test-erice', 'IT', 'Erice', 8, 'Trapani', 'Sicily', 'Italy') RETURNING id`,
    );
    const milano = await pool.query(
      `INSERT INTO localities (locality_hash, country_code, name, admin_level, county, region, country)
       VALUES ('ics-test-milano', 'IT', 'Milano', 8, 'Milano', 'Lombardy', 'Italy') RETURNING id`,
    );
    await pool.query(
      `INSERT INTO presences (photo_date, locality_id, photo_count) VALUES
         ('2025-08-10', $1, 3),
         ('2025-08-15', $1, 1),
         ('2025-08-10', $2, 2)`,
      [erice.rows[0].id, milano.rows[0].id],
    );

    const res = await request(server).get(`/api/trips/${tripId}/ics`);
    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toMatch(/text\/calendar/);
    expect(res.headers["content-disposition"]).toContain("attachment");
    expect(res.headers["content-disposition"]).toContain(".ics");

    const ics = res.text;
    expect(ics).toContain("BEGIN:VCALENDAR");
    expect(ics).toContain("END:VCALENDAR");
    expect(ics).toContain("BEGIN:VEVENT");
    expect(ics).toContain("END:VEVENT");
    expect(ics).toContain("SUMMARY:Sicilia");
    // DTSTART inclusive, DTEND exclusive (08-24 → 08-25).
    expect(ics).toContain("DTSTART;VALUE=DATE:20250810");
    expect(ics).toContain("DTEND;VALUE=DATE:20250825");
    // LOCATION is the locality with the most photos (Erice, 4 total).
    expect(ics).toContain("LOCATION:Erice");
    // DESCRIPTION carries the hierarchy + "Creato da Travelog".
    expect(ics).toContain(
      "DESCRIPTION:Erice\\, Trapani\\, Sicily\\, Italy\\nCreato da Travelog",
    );
    expect(ics).toContain(`UID:trip-${tripId}@travelog`);
  });

  it("omits LOCATION and uses only the signature when the trip has no locality", async () => {
    const tripId = await insertTrip("Manuale", "2025-09-01", "2025-09-03");

    const res = await request(server).get(`/api/trips/${tripId}/ics`);
    expect(res.status).toBe(200);
    const ics = res.text;
    expect(ics).not.toContain("LOCATION:");
    expect(ics).toContain("DESCRIPTION:Creato da Travelog");
  });

  it("returns 404 for a non-existent trip", async () => {
    const res = await request(server).get("/api/trips/999999/ics");
    expect(res.status).toBe(404);
    expect(res.body.code).toMatch(/TRIP_NOT_FOUND|trip_not_found/);
  });

  it("picks the manual-day locality when no presences exist", async () => {
    const tripId = await insertTrip("Manuale con località", "2025-10-01", "2025-10-02", {
      autoGenerated: false,
    });
    const locality = await pool.query(
      `INSERT INTO localities (locality_hash, country_code, name, admin_level, county, region, country)
       VALUES ('ics-test-manual', 'IT', 'Lozon', 8, 'Locarno', 'Ticino', 'Switzerland') RETURNING id`,
    );
    // Insert a manual day with a locality (no presences).
    const day = await pool.query(
      `INSERT INTO manual_trip_days (trip_id, day_date) VALUES ($1, '2025-10-01'::date) RETURNING id`,
      [tripId],
    );
    await pool.query(
      `INSERT INTO manual_trip_day_localities (day_id, locality_id) VALUES ($1, $2)`,
      [day.rows[0].id, locality.rows[0].id],
    );

    const res = await request(server).get(`/api/trips/${tripId}/ics`);
    expect(res.status).toBe(200);
    const ics = res.text;
    expect(ics).toContain("LOCATION:Lozon");
    expect(ics).toContain(
      "DESCRIPTION:Lozon\\, Locarno\\, Ticino\\, Switzerland\\nCreato da Travelog",
    );
  });
});
