/**
 * Travelog MVP1 — Trip generation integration tests (Phase 5)
 *
 * Uses the real PostgreSQL test database (travelog_test).
 * Covers: presence rebuild from photos, trip generation with the
 * functional requirements' rules, trip immutability on repeated runs,
 * exclusion zones, visit threshold and the §10.6 contiguity case.
 */

import { describe, it, expect, beforeEach, afterAll } from "vitest";
import { pool } from "../db/client.js";
import presencesRepository from "../repositories/presences.repository.js";
import tripsRepository from "../repositories/trips.repository.js";
import exclusionZonesRepository from "../repositories/exclusion-zones.repository.js";
import tripCalculationService from "../services/trip-calculation.service.js";
import { upsertPresence } from "../repositories/presences.repository.js";

const GEO_FIELDS = { countryCode: "IT", county: "TestCounty", region: "TestRegion" };

// ── Fixtures ─────────────────────────────────────────────────

async function insertLocality(hash: string, name: string): Promise<number> {
  const res = await pool.query(
    `INSERT INTO localities (locality_hash, country_code, name, admin_level, county, region, country)
     VALUES ($1, 'IT', $2, 8, 'TestCounty', 'TestRegion', 'Italy') RETURNING id`,
    [hash, name],
  );
  return res.rows[0].id as number;
}

async function insertCache(lat: number, lon: number, hash: string, localityId: number) {
  await pool.query(
    `INSERT INTO geocoding_cache (original_latitude, original_longitude, locality_hash, locality_id, country_code, name, admin_level, geo_applied)
     VALUES ($1, $2, $3, $4, 'IT', 'X', 8, true)`,
    [lat, lon, hash, localityId],
  );
}

async function insertPhotos(
  filePath: string,
  count: number,
  dateTime: string,
  lat: number,
  lon: number,
) {
  for (let i = 0; i < count; i++) {
    await pool.query(
      `INSERT INTO photos (file_path, file_name, file_type, size, mtime, date_time_original, original_latitude, original_longitude, metadata_status)
       VALUES ($1, $2, 'jpg', 100, $3, $4, $5, $6, 'valid')`,
      [filePath, `p${i}.jpg`, 1700000000 + i, dateTime, lat, lon],
    );
  }
}

async function listTrips() {
  const res = await pool.query(
    `SELECT id, name, to_char(start_date,'YYYY-MM-DD') AS s, to_char(end_date,'YYYY-MM-DD') AS e,
            auto_generated, status
     FROM trips ORDER BY start_date`,
  );
  return res.rows.map((r) => ({
    id: Number(r.id),
    name: r.name,
    startDate: r.s,
    endDate: r.e,
    autoGenerated: r.auto_generated,
    status: r.status,
  }));
}

async function setSettings(min: number, gap: number) {
  await pool.query("DELETE FROM settings");
  await pool.query(
    `INSERT INTO settings (id, min_consecutive_days_with_photos, days_without_photos_threshold)
     VALUES (1, $1, $2)
     ON CONFLICT (id) DO UPDATE SET
       min_consecutive_days_with_photos = EXCLUDED.min_consecutive_days_with_photos,
       days_without_photos_threshold = EXCLUDED.days_without_photos_threshold`,
    [min, gap],
  );
}

async function insertManualTrip(startDate: string, endDate: string): Promise<number> {
  const trip = await tripsRepository.createAutoTrip({
    name: "Viaggio manuale",
    startDate,
    endDate,
  });
  await pool.query(`UPDATE trips SET auto_generated = false WHERE id = $1`, [trip.id]);
  return trip.id;
}

// ── Cleanup ──────────────────────────────────────────────────

async function cleanup() {
  await pool.query("DELETE FROM photos WHERE file_path LIKE 'trip-test/%'");
  await pool.query("DELETE FROM exclusion_zones");
  await pool.query("TRUNCATE presences RESTART IDENTITY");
  await pool.query("TRUNCATE trips, trip_history RESTART IDENTITY");
  await pool.query("DELETE FROM geocoding_cache WHERE locality_hash LIKE 'trip-test-%'");
  await pool.query("DELETE FROM localities WHERE locality_hash LIKE 'trip-test-%'");
  await pool.query("DELETE FROM settings");
}

beforeEach(async () => {
  await cleanup();
});

// ── Tests ────────────────────────────────────────────────────

describe("presences repository", () => {
  it("rebuilds presences from photos with correct day + locality counts", async () => {
    const erice = await insertLocality("trip-test-erice", "Erice");
    const milano = await insertLocality("trip-test-milano", "Milano");
    await insertCache(38.03, 12.58, "trip-test-erice", erice);
    await insertCache(45.46, 9.19, "trip-test-milano", milano);

    await insertPhotos("trip-test/a", 3, "2025-08-10 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/b", 2, "2025-08-10 18:00:00", 45.46, 9.19);
    await insertPhotos("trip-test/c", 1, "2025-08-12 09:00:00", 38.03, 12.58);

    await presencesRepository.rebuildFromPhotos();
    let rows = await presencesRepository.listPresences();
    expect(rows).toHaveLength(3);
    expect(rows).toContainEqual({
      photoDate: "2025-08-10",
      localityId: erice,
      photoCount: 3,
      name: "Erice",
      ...GEO_FIELDS,
    });
    expect(rows).toContainEqual({
      photoDate: "2025-08-10",
      localityId: milano,
      photoCount: 2,
      name: "Milano",
      ...GEO_FIELDS,
    });
    expect(rows).toContainEqual({
      photoDate: "2025-08-12",
      localityId: erice,
      photoCount: 1,
      name: "Erice",
      ...GEO_FIELDS,
    });

    // Rebuild is idempotent (no duplications, §21.2)
    await presencesRepository.rebuildFromPhotos();
    rows = await presencesRepository.listPresences();
    expect(rows).toHaveLength(3);
    expect(rows[0].photoCount).toBe(3);
  });

  it("upserts presences incrementally", async () => {
    const erice = await insertLocality("trip-test-erice", "Erice");
    for (const time of ["2025-08-10T10:00:00", "2025-08-10T15:00:00"]) {
      const client = await pool.connect();
      try {
        await client.query("BEGIN");
        await upsertPresence(client, new Date(time), erice);
        await client.query("COMMIT");
      } finally {
        client.release();
      }
    }
    const rows = await presencesRepository.listPresences();
    expect(rows).toEqual([
      { photoDate: "2025-08-10", localityId: erice, photoCount: 2, name: "Erice", ...GEO_FIELDS },
    ]);
  });
});

describe("trip generation", () => {
  it("generates a trip per the §10.5 worked example and is idempotent", async () => {
    const erice = await insertLocality("trip-test-erice", "Erice");
    const milano = await insertLocality("trip-test-milano", "Milano");
    await insertCache(38.03, 12.58, "trip-test-erice", erice);
    await insertCache(45.46, 9.19, "trip-test-milano", milano);
    // min = 1 consecutive day: single-day visits qualify (as in §10.5)
    await setSettings(1, 3);

    await insertPhotos("trip-test/a", 3, "2025-08-10 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/b", 1, "2025-08-11 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/c", 1, "2025-08-13 10:30:00", 38.03, 12.58);
    // Photos only inside an exclusion zone: never a travel day
    await insertPhotos("trip-test/d", 2, "2025-08-20 10:30:00", 45.46, 9.19);
    await exclusionZonesRepository.create(milano);

    await presencesRepository.rebuildFromPhotos();
    const result = await tripCalculationService.generateTrips();
    expect(result.tripsCreated).toBe(1);

    let trips = await listTrips();
    expect(trips).toEqual([
      {
        id: trips[0].id,
        name: "Viaggio 2025-08-10",
        startDate: "2025-08-10",
        endDate: "2025-08-13",
        autoGenerated: true,
        status: "active",
      },
    ]);

    // Repeated generation never duplicates or modifies existing trips (§11)
    const second = await tripCalculationService.generateTrips();
    expect(second.tripsCreated).toBe(0);
    trips = await listTrips();
    expect(trips).toHaveLength(1);
  });
});

describe("contiguity and exclusion rules", () => {
  it("does NOT create trips from clipping fragments shorter than the minimum consecutive days", async () => {
    const erice = await insertLocality("trip-test-frag-erice", "Erice");
    await insertCache(38.03, 12.58, "trip-test-frag-erice", erice);
    await setSettings(3, 3);

    // An existing trip blocks most of the candidate run, leaving a
    // 1-day fragment (02 July) — exactly the user-reported scenario.
    await insertManualTrip("2025-07-03", "2025-07-31");

    await insertPhotos("trip-test/frag-a", 1, "2025-07-02 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/frag-b", 1, "2025-07-03 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/frag-c", 1, "2025-07-04 10:30:00", 38.03, 12.58);

    await presencesRepository.rebuildFromPhotos();
    const result = await tripCalculationService.generateTrips();

    // The 1-day fragment 02/07 must NOT become a trip.
    expect(result.tripsCreated).toBe(0);
    const trips = await listTrips();
    expect(trips.every((t) => t.startDate !== "2025-07-02")).toBe(true);
  });

  it("creates a NEW trip for photos contiguous to an existing trip (§10.6)", async () => {
    const erice = await insertLocality("trip-test-erice", "Erice");
    await insertCache(38.03, 12.58, "trip-test-erice", erice);
    await setSettings(1, 3);

    // First scan already consolidated trip A: 10–11 August
    await insertManualTrip("2025-08-10", "2025-08-11");

    await insertPhotos("trip-test/a", 1, "2025-08-10 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/b", 1, "2025-08-11 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/c", 1, "2025-08-12 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/d", 1, "2025-08-13 10:30:00", 38.03, 12.58);

    await presencesRepository.rebuildFromPhotos();
    const result = await tripCalculationService.generateTrips();
    expect(result.tripsCreated).toBe(1);

    const trips = await listTrips();
    expect(trips).toHaveLength(2);
    expect(trips[0]).toMatchObject({
      startDate: "2025-08-10",
      endDate: "2025-08-11",
      autoGenerated: false,
    });
    expect(trips[1]).toMatchObject({
      startDate: "2025-08-12",
      endDate: "2025-08-13",
      autoGenerated: true,
    });
  });

  it("requires the minimum consecutive days with photos (user request)", async () => {
    const erice = await insertLocality("trip-test-erice", "Erice");
    await insertCache(38.03, 12.58, "trip-test-erice", erice);
    await setSettings(2, 3);

    // A single day with photos: run of 1 < 2 → no trips
    await insertPhotos("trip-test/a", 10, "2025-08-10 10:30:00", 38.03, 12.58);
    await presencesRepository.rebuildFromPhotos();
    let result = await tripCalculationService.generateTrips();
    expect(result.tripsCreated).toBe(0);
    expect(await listTrips()).toHaveLength(0);

    // A second consecutive day: run of 2 → trip
    await insertPhotos("trip-test/b", 10, "2025-08-11 10:30:00", 38.03, 12.58);
    await presencesRepository.rebuildFromPhotos();
    result = await tripCalculationService.generateTrips();
    expect(result.tripsCreated).toBe(1);
    expect(await listTrips()).toHaveLength(1);
  });

  it("keeps a mixed day as a travel day and closes immediately on full exclusion (§9.4/§9.5)", async () => {
    const erice = await insertLocality("trip-test-erice", "Erice");
    const milano = await insertLocality("trip-test-milano", "Milano");
    await insertCache(38.03, 12.58, "trip-test-erice", erice);
    await insertCache(45.46, 9.19, "trip-test-milano", milano);
    await exclusionZonesRepository.create(milano);
    await setSettings(1, 3);

    // 01–02 out of zone, 03 only at home (excluded → immediate closure),
    // 04 mixed day (excluded + out of zone → travel day)
    await insertPhotos("trip-test/a", 1, "2025-08-01 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/b", 1, "2025-08-02 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/c", 5, "2025-08-03 10:30:00", 45.46, 9.19);
    await insertPhotos("trip-test/d", 5, "2025-08-04 10:30:00", 45.46, 9.19);
    await insertPhotos("trip-test/e", 1, "2025-08-04 18:30:00", 38.03, 12.58);

    await presencesRepository.rebuildFromPhotos();
    const result = await tripCalculationService.generateTrips();
    expect(result.tripsCreated).toBe(2);

    const trips = await listTrips();
    expect(trips.map((t) => [t.startDate, t.endDate])).toEqual([
      ["2025-08-01", "2025-08-02"],
      ["2025-08-04", "2025-08-04"],
    ]);
  });

  it("applies a county-scope exclusion zone only within the same county", async () => {
    const erice = await insertLocality("trip-test-erice", "Erice");
    const trapani = await insertLocality("trip-test-trapani", "Trapani");
    await setSettings(1, 3);
    // Same county for both: a county exclusion must cover both localities
    await pool.query(`UPDATE localities SET county = 'Trapani' WHERE id IN ($1, $2)`, [
      erice,
      trapani,
    ]);
    const lodi = await insertLocality("trip-test-lodi", "Lodi");
    await pool.query(`UPDATE localities SET county = 'Lodi' WHERE id = $1`, [lodi]);
    await insertCache(38.03, 12.58, "trip-test-erice", erice);
    await insertCache(38.01, 12.5, "trip-test-trapani", trapani);
    await insertCache(45.31, 9.5, "trip-test-lodi", lodi);

    // Erice is the anchor: excluding its county applies to Erice AND Trapani
    await exclusionZonesRepository.create(erice, "county");

    await insertPhotos("trip-test/a", 1, "2025-08-01 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/b", 1, "2025-08-02 10:30:00", 38.01, 12.5);
    await insertPhotos("trip-test/c", 1, "2025-08-03 10:30:00", 45.31, 9.5);

    await presencesRepository.rebuildFromPhotos();
    const result = await tripCalculationService.generateTrips();
    // Only the Lodi day (different county) is a travel day
    expect(result.tripsCreated).toBe(1);
    const trips = await listTrips();
    expect(trips[0]).toMatchObject({ startDate: "2025-08-03", endDate: "2025-08-03" });
  });

  it("matches county variants across provider languages (Milan/Milano)", async () => {
    const erice = await insertLocality("trip-test-erice", "Erice");
    const milanese = await insertLocality("trip-test-cusano", "Cusano Milanino");
    await setSettings(1, 3);
    // Same province returned in two languages by the provider:
    // the zone is anchored on the "Milan" spelling, but the presence
    // carries the "Milano" variant.
    await pool.query(`UPDATE localities SET county = 'Milan' WHERE id = $1`, [erice]);
    await pool.query(`UPDATE localities SET county = 'Milano' WHERE id = $1`, [milanese]);
    await insertCache(38.03, 12.58, "trip-test-erice", erice);
    await insertCache(45.52, 9.09, "trip-test-cusano", milanese);

    await exclusionZonesRepository.create(erice, "county");

    await insertPhotos("trip-test/a", 1, "2025-08-01 10:30:00", 45.52, 9.09);
    await insertPhotos("trip-test/b", 1, "2025-08-02 10:30:00", 38.03, 12.58);

    await presencesRepository.rebuildFromPhotos();
    const result = await tripCalculationService.generateTrips();

    // The "Milano"-variant day is excluded like the "Milan" one: no trips
    expect(result.tripsCreated).toBe(0);
  });

  it("aggregates duplicate coordinate hashes of the same locality in the detail", async () => {
    // The same city resolved at two different rounded coordinates:
    // the detail shows ONE entry with the summed photo count.
    const erice1 = await insertLocality("trip-test-erice", "Erice");
    const erice2 = await insertLocality("trip-test-erice2", "Erice");
    await insertCache(38.03, 12.58, "trip-test-erice", erice1);
    await insertCache(38.04, 12.59, "trip-test-erice2", erice2);
    await insertPhotos("trip-test/a", 2, "2025-08-10 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/b", 3, "2025-08-10 11:30:00", 38.04, 12.59);
    await insertPhotos("trip-test/c", 4, "2025-08-11 10:30:00", 38.03, 12.58);
    await insertPhotos("trip-test/d", 6, "2025-08-11 11:30:00", 38.04, 12.59);
    await presencesRepository.rebuildFromPhotos();
    const result = await tripCalculationService.generateTrips();
    expect(result.tripsCreated).toBe(1);
    const trips = await listTrips();
    expect(trips[0]).toMatchObject({ startDate: "2025-08-10", endDate: "2025-08-11" });
    const days = await tripsRepository.getTripDays("2025-08-10", "2025-08-11");
    expect(days[0].localities).toHaveLength(1);
    expect(days[0].localities[0].photoCount).toBe(5);
    expect(days[1].localities).toHaveLength(1);
    expect(days[1].localities[0].photoCount).toBe(10);
  });

  it("orders localities within a day by earliest photo time", async () => {
    // Alessandria 08:00 vs Bergamo 06:00: Bergamo (earlier shoot time)
    // must be listed first even though it follows alphabetically.
    const alessandria = await insertLocality("trip-test-ord-a", "Alessandria");
    const bergamo = await insertLocality("trip-test-ord-b", "Bergamo");
    await insertCache(44.91, 8.61, "trip-test-ord-a", alessandria);
    await insertCache(45.69, 9.67, "trip-test-ord-b", bergamo);
    await insertPhotos("trip-test/ord-a", 1, "2025-08-10 08:00:00", 44.91, 8.61);
    await insertPhotos("trip-test/ord-b", 1, "2025-08-10 06:00:00", 45.69, 9.67);
    await presencesRepository.rebuildFromPhotos();
    const days = await tripsRepository.getTripDays("2025-08-10", "2025-08-10");
    expect(days[0].localities.map((l) => l.name)).toEqual(["Bergamo", "Alessandria"]);
  });

  it("generates no trips without photos", async () => {
    const result = await tripCalculationService.generateTrips();
    expect(result.tripsCreated).toBe(0);
  });
});

afterAll(async () => {
  await cleanup();
  await pool.end();
});
