/**
 * Travelog MVP1 — Trips Service
 *
 * Manual trip consultation and modification (list, detail §16,
 * rename §13.1, date change §13.2). Split/merge live in the dedicated
 * trip-operations service (explicit use cases, design §7.2/§47).
 */

import tripsRepository, {
  type TripDto,
  type TripDayDto,
} from "../repositories/trips.repository.js";
import { NotFoundError, ConflictError, ValidationError } from "../models/errors.js";
import { addDays } from "../domain/trip-rules.js";

export interface TripQueryOptions {
  status?: "active" | "archived";
  search?: string;
  sort: "startDateDesc" | "startDateAsc";
  page: number;
  pageSize: number;
}

export interface CreateTripInput {
  name?: string;
  startDate: string;
  endDate: string;
}

export interface TripDetailDto extends TripDto {
  days: TripDayDto[];
}

function assertValidDateRange(startDate: string, endDate: string): void {
  if (!startDate || !endDate) {
    throw new ValidationError("Date del viaggio non valide", { fields: ["startDate", "endDate"] });
  }
  if (startDate > endDate) {
    throw new ValidationError("La data inizio non può essere successiva alla data fine", {
      fields: ["startDate", "endDate"],
    });
  }
}

/**
 * Fill gaps of 1–2 consecutive days without photos with "Nessuna foto"
 * entries (requirements §16). Larger gaps are not listed.
 */
function withNoPhotoDays(days: TripDayDto[], tripStart: string, tripEnd: string): TripDayDto[] {
  const result: TripDayDto[] = [];
  const fillGap = (fromExclusive: string, toInclusive: string) => {
    if (toInclusive > tripEnd) toInclusive = tripEnd;
    const missing: string[] = [];
    let cursor = addDays(fromExclusive, 1);
    while (cursor <= toInclusive) {
      missing.push(cursor);
      cursor = addDays(cursor, 1);
    }
    // §16: only gaps of 1 or 2 days are listed
    if (missing.length > 0 && missing.length <= 2) {
      for (const date of missing) {
        result.push({ date, noPhotos: true, localities: [] });
      }
    }
  };

  let previous = addDays(tripStart, -1); // sentinel: nothing before the trip start
  for (const day of days) {
    fillGap(previous, addDays(day.date, -1));
    result.push(day);
    previous = day.date;
  }
  fillGap(previous, tripEnd);
  return result;
}

class TripsService {
  async listTrips(options: TripQueryOptions) {
    // Contract: by default only active trips are returned.
    const status = options.status ?? "active";
    return tripsRepository.listTrips({ ...options, status });
  }

  /**
   * Trip detail (§16): trip data plus the chronology of days with the
   * visited localities and photo counts; days without photos (gaps of
   * 1–2 days) are listed with the "no photos" flag.
   */
  async getTrip(id: number): Promise<TripDetailDto> {
    const trip = await tripsRepository.getTrip(id);
    if (!trip) throw new NotFoundError("Trip", id);
    const days = await tripsRepository.getTripDays(trip.startDate, trip.endDate);
    return { ...trip, days: withNoPhotoDays(days, trip.startDate, trip.endDate) };
  }

  async createTrip(input: CreateTripInput): Promise<TripDto> {
    assertValidDateRange(input.startDate, input.endDate);
    const overlaps = await tripsRepository.findOverlappingTrips(input.startDate, input.endDate);
    if (overlaps.length > 0) {
      throw new ConflictError("Il nuovo viaggio si sovrappone a un viaggio attivo", "TRIP_OVERLAP");
    }
    const trip = await tripsRepository.insertTrip({
      name: input.name?.trim() || "",
      startDate: input.startDate,
      endDate: input.endDate,
      autoGenerated: false,
    });
    console.log(`[trip] trip.created manual id=${trip.id}`);
    return trip;
  }

  async updateTrip(
    id: number,
    updates: Partial<{ name: string; startDate: string; endDate: string }>,
  ): Promise<TripDto> {
    const existing = await tripsRepository.getTrip(id);
    if (!existing) throw new NotFoundError("Trip", id);
    if (existing.status !== "active") {
      throw new ConflictError(
        "Il viaggio è archiviato e non può essere modificato",
        "TRIP_NOT_ACTIVE",
      );
    }

    const startDate = updates.startDate ?? existing.startDate;
    const endDate = updates.endDate ?? existing.endDate;
    assertValidDateRange(startDate, endDate);

    // §13.2 / §21.17: active trips must never overlap temporally.
    const overlaps = await tripsRepository.findOverlappingTrips(startDate, endDate, id);
    if (overlaps.length > 0) {
      throw new ConflictError(
        "La modifica sovrapporrebbe il viaggio a un altro viaggio attivo",
        "TRIP_OVERLAP",
      );
    }

    const updated = await tripsRepository.updateTrip(id, {
      name: updates.name?.trim(),
      startDate: updates.startDate,
      endDate: updates.endDate,
    });
    if (!updated) throw new NotFoundError("Trip", id);
    return updated;
  }
}

export default new TripsService();
