/**
 * Travelog MVP1 — Trips Service
 */

import { db } from "../db/client.js";
import { trips, tripStatusEnum } from "../db/schema.js";
import tripsRepository from "../repositories/trips.repository.js";
import { NotFoundError, ConflictError } from "../models/errors.js";
import { eq } from "drizzle-orm";

export interface TripQueryOptions {
  status?: "active" | "archived";
  search?: string;
  sort: "startDateDesc" | "startDateAsc";
  page: number;
  pageSize: number;
}

export interface CreateTripInput {
  name?: string;
  startDate: string;
  endDate: string;
}

class TripsService {
  async listTrips(
    options: TripQueryOptions,
  ): Promise<{ items: any[]; page: number; pageSize: number; total: number }> {
    return tripsRepository.listTrips(options);
  }

  async getTrip(id: number) {
    const trip = await tripsRepository.getTrip(id);
    if (!trip) throw new NotFoundError("Trip", id);
    return trip;
  }

  async createTrip(input: CreateTripInput) {
    // Check for overlapping active trips
    const overlaps = await tripsRepository.findOverlappingTrips(
      new Date(input.startDate),
      new Date(input.endDate),
    );
    if (overlaps.length > 0) {
      throw new ConflictError("New trip overlaps with existing active trip", "TRIP_OVERLAP");
    }

    const result = await db
      .insert(trips)
      .values({
        name: input.name ?? "",
        startDate: new Date(input.startDate),
        endDate: new Date(input.endDate),
        autoGenerated: false,
        status: tripStatusEnum.enumValues[0], // 'active'
      })
      .returning();

    return result[0];
  }

  async updateTrip(
    id: number,
    updates: Partial<{ name: string; startDate: string; endDate: string }>,
  ) {
    const existing = await tripsRepository.getTrip(id);
    if (!existing) throw new NotFoundError("Trip", id);

    // If dates are being changed, check for overlaps
    if (updates.startDate || updates.endDate) {
      const start = new Date(updates.startDate ?? existing.startDate);
      const end = new Date(updates.endDate ?? existing.endDate);
      const overlaps = await tripsRepository.findOverlappingTrips(start, end, id);
      if (overlaps.length > 0) {
        throw new ConflictError("Update would overlap with another active trip", "TRIP_OVERLAP");
      }
    }

    const result = await db
      .update(trips)
      .set({
        ...(updates.name && { name: updates.name }),
        ...(updates.startDate && { startDate: new Date(updates.startDate) }),
        ...(updates.endDate && { endDate: new Date(updates.endDate) }),
        updatedAt: new Date(),
      })
      .where(eq(trips.id, id))
      .returning();

    return result[0];
  }
}

export default new TripsService();
