import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../repositories/presences.repository.js", () => ({
  default: { rebuildFromPhotos: vi.fn(), listPresences: vi.fn() },
}));
vi.mock("../repositories/trips.repository.js", () => ({
  default: { listActiveTripIntervals: vi.fn(), createAutoTrip: vi.fn() },
}));
vi.mock("../repositories/exclusion-zones.repository.js", () => ({
  default: { list: vi.fn() },
}));
vi.mock("./settings.service.js", () => ({ default: { getSettings: vi.fn() } }));
vi.mock("../config/logger.js", () => ({ default: { info: vi.fn() } }));

import presences from "../repositories/presences.repository.js";
import trips from "../repositories/trips.repository.js";
import zones from "../repositories/exclusion-zones.repository.js";
import settings from "./settings.service.js";
import service from "./trip-calculation.service.js";

beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(presences.rebuildFromPhotos).mockResolvedValue(undefined);
  vi.mocked(presences.listPresences).mockResolvedValue(
    ["2024-09-12", "2024-09-13", "2026-09-11", "2026-09-12", "2026-09-13", "2026-09-14"].map(
      (photoDate) => ({
        photoDate,
        localityId: 1,
        photoCount: 1,
        name: "Roma",
        countryCode: "IT",
        county: "Roma",
        region: "Lazio",
      }),
    ),
  );
  vi.mocked(zones.list).mockResolvedValue([]);
  vi.mocked(settings.getSettings).mockResolvedValue({
    minimumConsecutiveDaysWithPhotos: 2,
    consecutiveDaysWithoutPhotosBeforeClosing: 3,
  });
  vi.mocked(trips.listActiveTripIntervals).mockResolvedValue([]);
  vi.mocked(trips.createAutoTrip).mockImplementation(
    async (input) =>
      ({
        ...input,
        id: 1,
        status: "active",
        autoGenerated: true,
      }) as Awaited<ReturnType<typeof trips.createAutoTrip>>,
  );
});

describe("recalculation photo-date window", () => {
  it("generates only inside inclusive boundaries, ignoring adjacent and historical days", async () => {
    expect(await service.recalculate({ startDate: "2026-09-12", endDate: "2026-09-13" })).toEqual({
      tripsCreated: 1,
    });
    expect(presences.rebuildFromPhotos).toHaveBeenCalledOnce();
    expect(trips.createAutoTrip).toHaveBeenCalledExactlyOnceWith({
      name: "Viaggio 2026-09-12",
      startDate: "2026-09-12",
      endDate: "2026-09-13",
    });
  });
});
