/**
 * Travelog MVP1 — Trip Operations Service (Phase 6)
 *
 * Explicit use cases for the manual trip operations (technical design
 * §47): split (§13.3) and merge (§13.4). Not generic CRUD.
 *
 * Domain invariants enforced before committing:
 * - the split date belongs to the second trip;
 * - the merge result spans the earliest start and the latest end;
 * - active trips must never overlap temporally (§13.2, §21.17);
 * - the original trips are never deleted: they are archived (marked as
 *   superseded) and the operation is recorded in the audit trail (§14).
 *
 * Every operation is atomic (technical design §64).
 */

import { pool as dbPool } from "../db/client.js";
import type { PoolClient } from "pg";
import tripsRepository from "../repositories/trips.repository.js";
import operationsRepository from "../repositories/operations.repository.js";
import type { TripDto } from "../repositories/trips.repository.js";
import type { TripOperationDto as HistoryOperationDto } from "../repositories/operations.repository.js";

import { NotFoundError, ConflictError, ValidationError } from "../models/errors.js";
import {
  isValidSplitDate,
  computeSplitIntervals,
  proposeSplitTripName,
  computeMergeInterval,
} from "../domain/trip-operations.js";

export interface TripOperationResultDto {
  operation: HistoryOperationDto;
  trips: TripDto[];
}

/**
 * Group the flat manual day rows of the source trips into
 * day → localityIds entries for the copy (a source day may have zero
 * localities).
 */
function groupRowsByDate(
  rows: Array<{ dayDate: string; localityId: number | null }>,
): Array<{ dayDate: string; localityIds: number[] }> {
  const byDate = new Map<string, number[]>();
  for (const row of rows) {
    if (!byDate.has(row.dayDate)) byDate.set(row.dayDate, []);
    if (row.localityId !== null && !byDate.get(row.dayDate)!.includes(row.localityId)) {
      byDate.get(row.dayDate)!.push(row.localityId);
    }
  }
  return [...byDate.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([dayDate, localityIds]) => ({ dayDate, localityIds }));
}

class TripOperationsService {
  /**
   * Split a trip at the given date (§13.3). The split date belongs to
   * the second trip; the first trip keeps the original name; the second
   * name is the one provided by the user or system-proposed.
   */
  async splitTrip(
    tripId: number,
    splitDate: string,
    name?: string,
  ): Promise<TripOperationResultDto> {
    if (!splitDate) {
      throw new ValidationError("Data di divisione non valida", { fields: ["splitDate"] });
    }
    const original = await tripsRepository.getTrip(tripId);
    if (!original) throw new NotFoundError("Trip", tripId);
    if (original.status !== "active") {
      throw new ConflictError("Il viaggio è archiviato e non può essere diviso", "TRIP_NOT_ACTIVE");
    }
    if (!isValidSplitDate(original.startDate, original.endDate, splitDate)) {
      throw new ValidationError(
        "La data di divisione deve essere successiva all'inizio e non successiva alla fine del viaggio",
        { fields: ["splitDate"] },
      );
    }

    const [firstInterval, secondInterval] = computeSplitIntervals(
      original.startDate,
      original.endDate,
      splitDate,
    );
    return this.runInTransaction(async (client) => {
      // Manual days are copied to the resulting trips by date (the
      // archived original keeps its own rows for the audit history).
      const manualDays = groupRowsByDate(await tripsRepository.listManualDayRows([tripId]));
      await tripsRepository.archiveTrips([tripId], client);
      // §13.3: the first trip keeps the original name. Both results
      // inherit the manual-creation provenance of the original trip
      // (a split of a manual trip still contains the user-authored days).
      const first = await tripsRepository.insertTrip(
        {
          name: original.name,
          startDate: firstInterval.startDate,
          endDate: firstInterval.endDate,
          autoGenerated: original.autoGenerated,
          createdManually: original.createdManually,
        },
        client,
      );
      const second = await tripsRepository.insertTrip(
        {
          name: name?.trim() || proposeSplitTripName(original.name),
          startDate: secondInterval.startDate,
          endDate: secondInterval.endDate,
          autoGenerated: false,
          createdManually: original.createdManually,
        },
        client,
      );
      const firstDays = manualDays.filter((d) => d.dayDate < splitDate);
      const secondDays = manualDays.filter((d) => d.dayDate >= splitDate);
      await tripsRepository.insertManualDays(first.id, firstDays, client);
      await tripsRepository.insertManualDays(second.id, secondDays, client);
      const operation = await operationsRepository.insertOperation(client, {
        operation: "split",
        tripId,
        originalTripIds: [tripId],
        resultTripIds: [first.id, second.id],
        details: { splitDate },
      });
      console.log(`[trip] trip.split original=${tripId} results=${first.id},${second.id}`);
      return { operation, trips: [first, second] };
    });
  }

  /**
   * Merge two or more trips (§13.4). The resulting trip spans the union
   * interval and its default name is the first selected trip's name.
   * The original trips are archived, not deleted.
   */
  async mergeTrips(tripIds: number[], title?: string): Promise<TripOperationResultDto> {
    if (!Array.isArray(tripIds) || tripIds.length < 2) {
      throw new ValidationError("Servono almeno due viaggi da unire", { fields: ["tripIds"] });
    }
    const uniqueIds = [...new Set(tripIds)];
    const trips: TripDto[] = [];
    for (const id of uniqueIds) {
      const trip = await tripsRepository.getTrip(id);
      if (!trip) throw new NotFoundError("Trip", id);
      if (trip.status !== "active") {
        throw new ConflictError(
          `Il viaggio ${id} è archiviato e non può essere unito`,
          "TRIP_NOT_ACTIVE",
        );
      }
      trips.push(trip);
    }

    const interval = computeMergeInterval(
      trips.map((t) => ({ startDate: t.startDate, endDate: t.endDate })),
    );

    // §21.17: the merged trip must not overlap other active trips
    // outside the merge set.
    const overlaps = (
      await tripsRepository.findOverlappingTrips(interval.startDate, interval.endDate)
    ).filter((t) => !uniqueIds.includes(t.id));
    if (overlaps.length > 0) {
      throw new ConflictError(
        "L'unione sovrapporrebbe il viaggio risultante ad altri viaggi attivi",
        "TRIP_OVERLAP",
      );
    }

    return this.runInTransaction(async (client) => {
      // Manual days of all merged trips are copied to the resulting trip
      // (the archived originals keep their own rows for the history);
      // shared day/locality pairs are merged without duplication.
      const manualDays = groupRowsByDate(await tripsRepository.listManualDayRows(uniqueIds));
      await tripsRepository.archiveTrips(uniqueIds, client);
      // §13.4: default name is the first selected trip's name. The
      // result carries the manual-creation provenance when at least one
      // merged trip is manual (its user-authored days are copied into
      // the result).
      const merged = await tripsRepository.insertTrip(
        {
          name: title?.trim() || trips[0].name,
          startDate: interval.startDate,
          endDate: interval.endDate,
          autoGenerated: false,
          createdManually: trips.some((t) => t.createdManually),
        },
        client,
      );
      await tripsRepository.insertManualDays(merged.id, manualDays, client);
      const operation = await operationsRepository.insertOperation(client, {
        operation: "merge",
        tripId: uniqueIds[0],
        originalTripIds: uniqueIds,
        resultTripIds: [merged.id],
        details: {
          mergedIntervals: trips.map((t) => ({ startDate: t.startDate, endDate: t.endDate })),
        },
      });
      console.log(`[trip] trip.merged sources=${uniqueIds.join(",")} result=${merged.id}`);
      return { operation, trips: [merged] };
    });
  }

  /**
   * Explicitly delete a trip (user request: some generated periods are
   * not trips). The audit trail records the deletion — with a snapshot
   * of the deleted trip — BEFORE the row is removed, so the history
   * survives the delete (requirements §14).
   */
  async deleteTrip(tripId: number): Promise<void> {
    const trip = await tripsRepository.getTrip(tripId);
    if (!trip) throw new NotFoundError("Trip", tripId);

    return this.runInTransaction(async (client) => {
      await operationsRepository.insertOperation(client, {
        operation: "delete",
        // tripId stays NULL: trip_history rows referencing the trip are
        // deleted by cascade, so the audit entry must not point to it.
        tripId: null,
        originalTripIds: [tripId],
        resultTripIds: [],
        details: {
          name: trip.name,
          startDate: trip.startDate,
          endDate: trip.endDate,
          autoGenerated: trip.autoGenerated,
          status: trip.status,
        },
      });
      await tripsRepository.deleteTrip(tripId);
      console.log(`[trip] trip.deleted id=${tripId} (${trip.startDate} → ${trip.endDate})`);
    });
  }

  private async runInTransaction<T>(work: (client: PoolClient) => Promise<T>): Promise<T> {
    const client = await dbPool.connect();
    try {
      await client.query("BEGIN");
      const result = await work(client);
      await client.query("COMMIT");
      return result;
    } catch (err) {
      await client.query("ROLLBACK").catch(() => undefined);
      throw err;
    } finally {
      client.release();
    }
  }
}

export default new TripOperationsService();
