/**
 * Travelog MVP1 — Trips Repository
 *
 * All date values are naive ISO strings (YYYY-MM-DD) serialized in SQL
 * with to_char / cast with ::date: JS Date round-trips shift the calendar
 * day via UTC conversion (naive local time, requirements §5.2).
 */

import { db, pool as dbPool } from "../db/client.js";
import { trips } from "../db/schema.js";
import { eq, and, or, ilike, count, desc, asc, sql } from "drizzle-orm";
import type { PoolClient } from "pg";
import type { TripQueryOptions } from "../services/trips.service.js";

export interface TripDto {
  id: number;
  name: string;
  /** Naive ISO date, YYYY-MM-DD. */
  startDate: string;
  /** Naive ISO date, YYYY-MM-DD. */
  endDate: string;
  autoGenerated: boolean;
  /** True ONLY for trips created via the manual creation endpoint. */
  createdManually: boolean;
  status: string;
  createdAt: string;
  /** Total number of valid photos in the trip (from presences). */
  photoCount: number;
  /** Distinct administrative levels visited (county + region), sorted. */
  regions: string[];
}

export interface TripDayLocalityDto {
  localityId: number;
  name: string;
  county: string | null;
  region: string | null;
  country: string | null;
  photoCount: number;
  /** True when the day/locality was entered manually by the user. */
  manual: boolean;
}

export interface TripDayDto {
  /** Naive ISO date, YYYY-MM-DD. */
  date: string;
  /** True for days without photos ("Nessuna foto", §16). */
  noPhotos: boolean;
  localities: TripDayLocalityDto[];
  /** True when the day was created manually by the user. */
  manual: boolean;
}

/** Marker data for trip map visualization — one entry per locality listed
    in the trip detail (§16), aggregated by administrative name and ordered
    chronologically. `firstPhotoAt` is null for manual localities without
    photos. */
export interface MapMarkerDto {
  localityId: number;
  name: string;
  latitude: number;
  longitude: number;
  photoCount: number;
  firstPhotoAt: string | null;
  county: string | null;
  region: string | null;
  country: string | null;
}

export interface BoundingBoxDto {
  minLat: number;
  minLon: number;
  maxLat: number;
  maxLon: number;
}

const tripSelection = {
  id: trips.id,
  name: trips.name,
  startDate: sql<string>`to_char(${trips.startDate}, 'YYYY-MM-DD')`,
  endDate: sql<string>`to_char(${trips.endDate}, 'YYYY-MM-DD')`,
  autoGenerated: trips.autoGenerated,
  createdManually: trips.createdManually,
  status: trips.status,
  createdAt: sql<string>`to_char(${trips.createdAt}, 'YYYY-MM-DD"T"HH24:MI:SS')`,
};

function mapTripRow(row: Record<string, unknown>): TripDto {
  return {
    id: Number(row.id),
    name: String(row.name),
    startDate: String(row.startDate),
    endDate: String(row.endDate),
    autoGenerated: Boolean(row.autoGenerated),
    createdManually: Boolean(row.created_manually ?? row.createdManually),
    status: String(row.status),
    createdAt: String(row.createdAt),
    photoCount: Number(row.photo_count ?? 0),
    regions: (row.regions as string[]) ?? [],
  };
}

class TripsRepository {
  async listTrips(options: TripQueryOptions): Promise<{
    items: TripDto[];
    page: number;
    pageSize: number;
    total: number;
  }> {
    const { status, search, sort, page, pageSize } = options;
    const offset = (page - 1) * pageSize;

    const conditions: ReturnType<typeof eq>[] = [];
    if (status) {
      conditions.push(eq(trips.status, status));
    }

    let finalCondition: ReturnType<typeof and> | undefined = undefined;
    if (conditions.length > 0 || search) {
      let searchCondition: ReturnType<typeof or> | undefined = undefined;
      if (search) {
        const pattern = `%${search}%`;
        searchCondition = or(
          ilike(trips.name, pattern),
          sql`EXTRACT(YEAR FROM ${trips.startDate})::TEXT LIKE ${pattern}`,
        );
      }

      if (conditions.length > 0 && searchCondition) {
        finalCondition = and(...conditions, searchCondition);
      } else if (conditions.length > 0) {
        finalCondition = and(...conditions);
      } else if (searchCondition) {
        finalCondition = searchCondition;
      }
    }

    const orderBy = sort === "startDateAsc" ? asc(trips.startDate) : desc(trips.startDate);

    const countResult = await db.select({ total: count() }).from(trips).where(finalCondition);
    const totalCount = countResult[0]?.total ?? 0;

    // Fetch basic trip data (using Drizzle for correct SQL generation),
    // then enrich with photoCount/regions computed from presences.
    const rows = await db
      .select(tripSelection)
      .from(trips)
      .where(finalCondition)
      .orderBy(orderBy)
      .limit(pageSize)
      .offset(offset);

    return {
      items: await this.attachStats(rows.map(mapTripRow)),
      page,
      pageSize,
      total: totalCount,
    };
  }

  /**
   * Enriches trips with two fields used by the trip cards (new UI):
   * - photoCount: total photos in the trip, from the sum of the presences
   *   `photo_count` rows whose day falls inside the trip interval (§15/§16);
   * - regions: distinct administrative REGION names visited (the provinces
   *   are not used as tags), ordered alphabetically.
   * The presences join intentionally does NOT filter on `locality_id` at
   * the trip level: the interval fully identifies the trip's days.
   */
  private async attachStats(items: TripDto[]): Promise<TripDto[]> {
    if (items.length === 0) return items;
    const tripIds = items.map((t) => t.id);
    const statsRows = await dbPool.query(
      `SELECT t.id,
              COALESCE(SUM(p.photo_count), 0) AS photo_count,
              array_agg(DISTINCT l.region)
                FILTER (WHERE COALESCE(l.region, '') != '') AS regions
       FROM trips t
       LEFT JOIN presences p ON p.photo_date >= t.start_date AND p.photo_date <= t.end_date
       LEFT JOIN localities l ON l.id = p.locality_id
       WHERE t.id = ANY($1::int[])
       GROUP BY t.id`,
      [tripIds],
    );

    const statsMap = new Map<number, { photoCount: number; regions: string[] }>();
    for (const row of statsRows.rows) {
      const regions = ((row.regions as string[]) ?? []).sort((a, b) => a.localeCompare(b));
      statsMap.set(Number(row.id), {
        photoCount: Number(row.photo_count ?? 0),
        regions,
      });
    }

    return items.map((trip) => {
      const stats = statsMap.get(trip.id);
      return stats ? { ...trip, ...stats } : trip;
    });
  }

  async getTrip(id: number): Promise<TripDto | null> {
    const rows = await db.select(tripSelection).from(trips).where(eq(trips.id, id));
    if (rows.length === 0) return null;
    const [trip] = await this.attachStats([mapTripRow(rows[0])]);
    return trip;
  }

  /**
   * Active trips overlapping the given inclusive interval. `excludeId`
   * removes one trip from the check (the trip being modified itself).
   */
  async findOverlappingTrips(
    startDate: string,
    endDate: string,
    excludeId?: number,
  ): Promise<TripDto[]> {
    const result = await dbPool.query(
      `SELECT id, name,
              to_char(start_date, 'YYYY-MM-DD') AS "startDate",
              to_char(end_date, 'YYYY-MM-DD') AS "endDate",
              auto_generated AS "autoGenerated",
              created_manually AS "createdManually",
              status,
              to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS "createdAt"
       FROM trips
       WHERE status = 'active'
         AND start_date <= $2::date
         AND end_date >= $1::date
         AND ($3::int IS NULL OR id <> $3::int)
       ORDER BY start_date`,
      [startDate, endDate, excludeId ?? null],
    );
    return result.rows.map(mapTripRow);
  }

  /**
   * Presences (day + locality) inside an inclusive date interval,
   * ordered chronologically: the building blocks of the trip detail
   * (requirements §16). The same administrative locality can exist as
   * several `localities` rows (one per rounded coordinate hash): the
   * aggregation by locality name happens in the service layer.
   */
  async getTripDays(startDate: string, endDate: string): Promise<TripDayDto[]> {
    const result = await dbPool.query(
      `SELECT to_char(p.photo_date, 'YYYY-MM-DD') AS day,
              l.id AS locality_id, l.name, l.county, l.region, l.country,
              p.photo_count,
              (SELECT MIN(ph.date_time_original)
                 FROM photos ph
                 JOIN geocoding_cache gc
                   ON gc.original_latitude = ph.original_latitude
                  AND gc.original_longitude = ph.original_longitude
                  AND gc.locality_id = p.locality_id
                WHERE ph.date_time_original IS NOT NULL
                  AND ph.date_time_original::date = p.photo_date) AS first_photo_at
       FROM presences p
       JOIN localities l ON l.id = p.locality_id
       WHERE p.photo_date >= $1::date AND p.photo_date <= $2::date
       ORDER BY p.photo_date, first_photo_at NULLS LAST, l.name`,
      [startDate, endDate],
    );
    const days: TripDayDto[] = [];
    let currentDate: string | null = null;
    let currentLocalities = new Map<string, TripDayLocalityDto>();

    const flushDay = () => {
      if (currentDate === null) return;
      days.push({
        date: currentDate,
        noPhotos: false,
        localities: [...currentLocalities.values()],
        manual: false,
      });
    };

    for (const r of result.rows) {
      const date = String(r.day);
      if (date !== currentDate) {
        flushDay();
        currentDate = date;
        currentLocalities = new Map();
      }
      // The same city can be present under several coordinate hashes:
      // aggregate by administrative name (§6.3/§7.2), summing the counts.
      const key = `${String(r.name).toLowerCase()}|${r.county ?? ""}|${r.region ?? ""}`;
      const existing = currentLocalities.get(key);
      if (existing) {
        existing.photoCount += Number(r.photo_count);
      } else {
        currentLocalities.set(key, {
          localityId: Number(r.locality_id),
          name: r.name,
          county: r.county ?? null,
          region: r.region ?? null,
          country: r.country ?? null,
          photoCount: Number(r.photo_count),
          manual: false,
        });
      }
    }
    flushDay();
    return days;
  }

  /**
   * Insert a trip. Used by automatic generation (Phase 5) and by the
   * manual operations (Phase 6). Optional transaction client keeps the
   * whole operation atomic (technical design §64).
   */
  async insertTrip(
    input: {
      name: string;
      startDate: string;
      endDate: string;
      autoGenerated: boolean;
      createdManually?: boolean;
    },
    tx?: PoolClient,
  ): Promise<TripDto> {
    const client = tx ?? dbPool;
    const result = await client.query(
      `INSERT INTO trips (name, start_date, end_date, auto_generated, created_manually, status)
       VALUES ($1, $2::date, $3::date, $4, $5, 'active')
       RETURNING id, name,
                 to_char(start_date, 'YYYY-MM-DD') AS start_date,
                 to_char(end_date, 'YYYY-MM-DD') AS end_date,
                 auto_generated, created_manually, status,
                 to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS created_at`,
      [
        input.name,
        input.startDate,
        input.endDate,
        input.autoGenerated,
        input.createdManually ?? false,
      ],
    );
    const r = result.rows[0];
    return {
      id: Number(r.id),
      name: r.name,
      startDate: r.start_date,
      endDate: r.end_date,
      autoGenerated: r.auto_generated,
      createdManually: r.created_manually,
      status: r.status,
      createdAt: r.created_at,
      photoCount: 0,
      regions: [],
    };
  }

  /**
   * Manual rename / date change (§13.1, §13.2). Undefined fields are
   * preserved.
   */
  async updateTrip(
    id: number,
    updates: { name?: string; startDate?: string; endDate?: string },
  ): Promise<TripDto | null> {
    const result = await dbPool.query(
      `UPDATE trips SET
         name       = COALESCE($2::text, name),
         start_date = COALESCE($3::date, start_date),
         end_date   = COALESCE($4::date, end_date),
         updated_at = now()
       WHERE id = $1::int
       RETURNING id, name,
                 to_char(start_date, 'YYYY-MM-DD') AS "startDate",
                 to_char(end_date, 'YYYY-MM-DD') AS "endDate",
                 auto_generated AS "autoGenerated",
                 created_manually AS "createdManually", status,
                 to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS "createdAt"`,
      [id, updates.name ?? null, updates.startDate ?? null, updates.endDate ?? null],
    );
    return result.rows.length > 0 ? mapTripRow(result.rows[0]) : null;
  }

  /**
   * Physically delete a trip (explicit user operation: some generated
   * periods are not trips). Returns true when a row was deleted.
   */
  async deleteTrip(id: number): Promise<boolean> {
    const result = await dbPool.query(`DELETE FROM trips WHERE id = $1::int`, [id]);
    return result.rowCount !== null && result.rowCount > 0;
  }

  /**
   * Mark trips as superseded (split/merge keep the originals in the
   * database — requirements §13.3, §13.4).
   */
  async archiveTrips(ids: number[], tx?: PoolClient): Promise<void> {
    const client = tx ?? dbPool;
    await client.query(
      `UPDATE trips SET status = 'archived', updated_at = now() WHERE id = ANY($1::int[])`,
      [ids],
    );
  }

  /**
   * Active trips as naive date intervals (YYYY-MM-DD, serialized in SQL
   * so the values are independent from the server timezone).
   * Used by trip generation to protect existing trips (immutability).
   */
  async listActiveTripIntervals(): Promise<
    Array<{ id: number; startDate: string; endDate: string }>
  > {
    const rows = await db
      .select({
        id: trips.id,
        startDate: sql<string>`to_char(${trips.startDate}, 'YYYY-MM-DD')`,
        endDate: sql<string>`to_char(${trips.endDate}, 'YYYY-MM-DD')`,
      })
      .from(trips)
      .where(eq(trips.status, "active"));
    return rows.map((r) => ({ id: r.id, startDate: r.startDate, endDate: r.endDate }));
  }

  /**
   * Insert an auto-generated trip (Phase 5 trip generation).
   */
  async createAutoTrip(input: { name: string; startDate: string; endDate: string }) {
    return this.insertTrip({ ...input, autoGenerated: true });
  }

  // ── Manual trip days (manual trip creation feature) ────────────────

  /**
   * Manual days (day + localities) of a single trip, ordered
   * chronologically. A manual day can have zero localities (it is added
   * to the trip before assigning them). photoCount is 0 and `manual` is
   * true: manual days are explicit user intent, not photographic
   * evidence.
   */
  async getManualDays(tripId: number): Promise<TripDayDto[]> {
    const result = await dbPool.query(
      `SELECT to_char(d.day_date, 'YYYY-MM-DD') AS day,
              l.id AS locality_id, l.name, l.county, l.region, l.country
       FROM manual_trip_days d
       LEFT JOIN manual_trip_day_localities m ON m.day_id = d.id
       LEFT JOIN localities l ON l.id = m.locality_id
       WHERE d.trip_id = $1::int
       ORDER BY d.day_date, l.name`,
      [tripId],
    );
    return this.groupManualRows(result.rows);
  }

  /**
   * Persisted day/locality exclusions of a trip ("delete day/locality"
   * on auto-generated trips). `localityKey` is the detail grouping key
   * (lower(name)|county|region, getTripDays §6.3/§7.2); null = the WHOLE
   * day is excluded.
   */
  async getDayExclusions(
    tripId: number,
  ): Promise<Array<{ dayDate: string; localityKey: string | null }>> {
    const result = await dbPool.query(
      `SELECT to_char(day_date, 'YYYY-MM-DD') AS "dayDate", locality_key AS "localityKey"
       FROM trip_day_exclusions
       WHERE trip_id = $1::int
       ORDER BY day_date, locality_key NULLS FIRST`,
      [tripId],
    );
    return result.rows.map((r) => ({
      dayDate: String(r.dayDate),
      localityKey:
        r.localityKey === null || r.localityKey === undefined ? null : String(r.localityKey),
    }));
  }

  /**
   * Atomically rewrite the day exclusions of a trip: the request of
   * PUT /trips/{tripId}/days is the authoritative desired state, so the
   * whole set is replaced (removed exclusions re-show the content —
   * explicit, reversible user operation). Optional transaction client
   * keeps the rewrite in the same transaction as the manual-day update.
   */
  async replaceDayExclusions(
    tripId: number,
    exclusions: Array<{ dayDate: string; localityKey: string | null }>,
    tx?: PoolClient,
  ): Promise<void> {
    const client = tx ?? dbPool;
    await client.query(`DELETE FROM trip_day_exclusions WHERE trip_id = $1::int`, [tripId]);
    for (const e of exclusions) {
      await client.query(
        `INSERT INTO trip_day_exclusions (trip_id, day_date, locality_key)
         VALUES ($1::int, $2::date, $3)
         ON CONFLICT DO NOTHING`,
        [tripId, e.dayDate, e.localityKey],
      );
    }
  }

  /**
   * Detail grouping key (lower(name)|county|region) of the given
   * localities: used to translate "add locality" requests into
   * exclusion removals when the user re-adds a previously excluded
   * locality.
   */
  async getLocalityKeys(localityIds: number[]): Promise<Map<number, string>> {
    if (localityIds.length === 0) return new Map();
    const result = await dbPool.query<{ id: number; key: string }>(
      `SELECT id,
              lower(name) || '|' || COALESCE(county, '') || '|' || COALESCE(region, '') AS key
       FROM localities
       WHERE id = ANY($1::int[])`,
      [localityIds],
    );
    return new Map(result.rows.map((r) => [Number(r.id), String(r.key)]));
  }

  /**
   * Flat manual day rows of the given trips (used by split/merge to copy
   * manual days to the resulting trips). `localityId` is null for days
   * without localities.
   */
  async listManualDayRows(
    sourceTripIds: number[],
  ): Promise<Array<{ tripId: number; dayDate: string; localityId: number | null }>> {
    if (sourceTripIds.length === 0) return [];
    const result = await dbPool.query(
      `SELECT d.trip_id AS "tripId",
              to_char(d.day_date, 'YYYY-MM-DD') AS "dayDate",
              m.locality_id AS "localityId"
       FROM manual_trip_days d
       LEFT JOIN manual_trip_day_localities m ON m.day_id = d.id
       WHERE d.trip_id = ANY($1::int[])
       ORDER BY d.day_date, m.locality_id`,
      [sourceTripIds],
    );
    return result.rows.map((r) => ({
      tripId: Number(r.tripId),
      dayDate: String(r.dayDate),
      localityId: r.localityId === null || r.localityId === undefined ? null : Number(r.localityId),
    }));
  }

  /**
   * Insert manual days (and their localities) for a trip. Used inside
   * the transactions of trip creation, day replacement and split/merge
   * copying. Existing (trip, date) days are kept — so merge can copy
   * days into an already-populated interval — and duplicate locality
   * links are skipped.
   */
  async insertManualDays(
    tripId: number,
    days: Array<{ dayDate: string; localityIds: number[] }>,
    tx?: PoolClient,
  ): Promise<void> {
    if (days.length === 0) return;
    const client = tx ?? dbPool;
    await client.query(
      `INSERT INTO manual_trip_days (trip_id, day_date)
       SELECT $1::int, x::date
       FROM unnest($2::date[]) AS x
       ON CONFLICT (trip_id, day_date) DO NOTHING`,
      [tripId, days.map((d) => d.dayDate)],
    );
    const idRows = await client.query(
      `SELECT id, to_char(day_date, 'YYYY-MM-DD') AS day_date
       FROM manual_trip_days
       WHERE trip_id = $1::int AND day_date = ANY($2::date[])`,
      [tripId, days.map((d) => d.dayDate)],
    );
    const idsByDate = new Map<string, number>();
    for (const r of idRows.rows) idsByDate.set(String(r.day_date), Number(r.id));
    const dayIds: number[] = [];
    const localityIds: number[] = [];
    for (const day of days) {
      const dayId = idsByDate.get(day.dayDate);
      if (dayId === undefined) continue;
      for (const localityId of day.localityIds) {
        dayIds.push(dayId);
        localityIds.push(localityId);
      }
    }
    if (dayIds.length === 0) return;
    await client.query(
      `INSERT INTO manual_trip_day_localities (day_id, locality_id)
       SELECT y::int, z::int
       FROM unnest($1::int[], $2::int[]) AS t(y, z)
       ON CONFLICT DO NOTHING`,
      [dayIds, localityIds],
    );
  }

  /**
   * Remove every manual day of a trip. Used inside the replacement
   * transaction; the physical trip delete relies on the ON DELETE
   * CASCADE foreign key instead.
   */
  async deleteManualDays(tripId: number, tx?: PoolClient): Promise<void> {
    const client = tx ?? dbPool;
    await client.query(`DELETE FROM manual_trip_days WHERE trip_id = $1::int`, [tripId]);
  }

  /**
   * Remove the manual days of a trip that fall outside the given
   * inclusive interval (invariant: manual days live inside the trip
   * interval, also after an explicit date change).
   */
  async deleteManualDaysOutsideRange(
    tripId: number,
    startDate: string,
    endDate: string,
  ): Promise<void> {
    await dbPool.query(
      `DELETE FROM manual_trip_days
       WHERE trip_id = $1::int
         AND (day_date < $2::date OR day_date > $3::date)`,
      [tripId, startDate, endDate],
    );
  }

  /**
   * Group raw manual day/locality rows into TripDayDto objects,
   * aggregating repeated locality names (same rule as getTripDays,
   * §6.3/§7.2).
   */
  private groupManualRows(rows: Record<string, unknown>[]): TripDayDto[] {
    const days: TripDayDto[] = [];
    let currentDate: string | null = null;
    let currentLocalities = new Map<string, TripDayLocalityDto>();

    const flushDay = () => {
      if (currentDate === null) return;
      days.push({
        date: currentDate,
        noPhotos: false,
        localities: [...currentLocalities.values()],
        manual: true,
      });
    };

    for (const r of rows) {
      const date = String(r.day);
      if (date !== currentDate) {
        flushDay();
        currentDate = date;
        currentLocalities = new Map();
      }
      // A manual day can have zero localities (LEFT JOIN miss): the day
      // row is still listed, with an empty localities list.
      if (r.locality_id === null) continue;
      const key = `${String(r.name).toLowerCase()}|${r.county ?? ""}|${r.region ?? ""}`;
      if (!currentLocalities.has(key)) {
        currentLocalities.set(key, {
          localityId: Number(r.locality_id),
          name: String(r.name),
          county: r.county != null ? String(r.county) : null,
          region: r.region != null ? String(r.region) : null,
          country: r.country != null ? String(r.country) : null,
          photoCount: 0,
          manual: true,
        });
      }
    }
    flushDay();
    return days;
  }

  /**
   * Retrieve marker data for trip map visualization (requirements §16 /
   * TripMap feature). The markers are derived from the SAME source as the
   * trip detail (§16): presence localities within the trip interval PLUS
   * the localities of the trip's manual days — so the map shows exactly
   * one waymark per locality listed in the detail panel, even for manual
   * localities without photos.
   *
   * The same administrative locality can exist as several `localities`
   * rows (one per rounded coordinate hash): the aggregation by locality
   * name (name + county + region, same rule as getTripDays §6.3/§7.2)
   * guarantees ONE marker per listed locality, with the summed photo
   * count and the coordinates of the representative row (preferably the
   * one with the earliest photo). Coordinates are extracted from the
   * `locality_hash` column in geocoding-cache-derived `localities` rows —
   * no extra columns or migrations needed.
   */
  async getTripMapData(
    tripId: number,
    startDate: string,
    endDate: string,
  ): Promise<{ markers: MapMarkerDto[]; bounds: BoundingBoxDto }> {
    const result = await dbPool.query(
      `WITH presence_rows AS (
         SELECT p.locality_id,
                l.name, l.county, l.region, l.country, l.locality_hash,
                p.photo_count,
                (SELECT MIN(ph.date_time_original)
                   FROM photos ph
                   JOIN geocoding_cache gc
                     ON gc.original_latitude = ph.original_latitude
                    AND gc.original_longitude = ph.original_longitude
                    AND gc.locality_id = p.locality_id
                  WHERE ph.date_time_original IS NOT NULL
                    AND ph.date_time_original::date = p.photo_date) AS first_photo_at,
                NULL::date AS first_day
         FROM presences p
         JOIN localities l ON l.id = p.locality_id
         WHERE p.photo_date >= $1::date AND p.photo_date <= $2::date
           -- Explicit day/locality exclusions ("delete day/locality" on
           -- auto trips): hide excluded days and excluded locality cards.
           AND NOT EXISTS (
             SELECT 1 FROM trip_day_exclusions e
             WHERE e.trip_id = $3::int
               AND e.day_date = p.photo_date
               AND (e.locality_key IS NULL
                    OR e.locality_key = lower(l.name) || '|' || COALESCE(l.county, '') || '|' || COALESCE(l.region, ''))
           )
       ),
       manual_rows AS (
         SELECT m.locality_id,
                l.name, l.county, l.region, l.country, l.locality_hash,
                0::int AS photo_count,
                NULL::timestamp AS first_photo_at,
                MIN(d.day_date) AS first_day
         FROM manual_trip_days d
         JOIN manual_trip_day_localities m ON m.day_id = d.id
         JOIN localities l ON l.id = m.locality_id
         WHERE d.trip_id = $3::int
         GROUP BY m.locality_id, l.name, l.county, l.region, l.country, l.locality_hash
       ),
       all_rows AS (
         SELECT * FROM presence_rows
         UNION ALL
         SELECT * FROM manual_rows
       ),
       aggregated AS (
         SELECT name,
                COALESCE(county, '') AS county_key,
                COALESCE(region, '') AS region_key,
                SUM(photo_count)::int AS photo_count,
                MIN(first_photo_at)   AS first_photo_at,
                MIN(first_day)        AS first_day
         FROM all_rows
         GROUP BY name, COALESCE(county, ''), COALESCE(region, '')
       ),
       representative AS (
         SELECT DISTINCT ON (r.name, COALESCE(r.county, ''), COALESCE(r.region, ''))
           r.locality_id, r.name, r.county, r.region, r.country, r.locality_hash,
           a.photo_count, a.first_photo_at, a.first_day
         FROM all_rows r
         JOIN aggregated a
           ON a.name = r.name
          AND a.county_key = COALESCE(r.county, '')
          AND a.region_key = COALESCE(r.region, '')
         WHERE r.locality_hash ~ '^-?[0-9]+\\.[0-9]+:-?[0-9]+\\.[0-9]+$'
         ORDER BY r.name, COALESCE(r.county, ''), COALESCE(r.region, ''),
                  r.first_photo_at NULLS LAST, r.locality_id
       )
       SELECT locality_id, name, county, region, country,
              photo_count, first_photo_at::text AS first_photo_at,
              split_part(locality_hash, ':', 1)::double precision AS latitude,
              split_part(locality_hash, ':', 2)::double precision AS longitude
       FROM representative
       ORDER BY COALESCE(first_photo_at, first_day::timestamp) NULLS LAST, name`,
      [startDate, endDate, tripId],
    );

    const markers: MapMarkerDto[] = result.rows.map((r) => ({
      localityId: Number(r.locality_id),
      name: String(r.name),
      latitude: parseFloat(String(r.latitude)),
      longitude: parseFloat(String(r.longitude)),
      photoCount: Number(r.photo_count),
      firstPhotoAt: r.first_photo_at != null ? String(r.first_photo_at) : null,
      county: r.county != null ? String(r.county) : null,
      region: r.region != null ? String(r.region) : null,
      country: r.country != null ? String(r.country) : null,
    }));

    // Compute bounding box from markers
    let bounds: BoundingBoxDto;
    if (markers.length === 0) {
      // Default center (Italy-ish) when no markers exist
      bounds = { minLat: 37, minLon: 6, maxLat: 47.1, maxLon: 19 };
    } else {
      bounds = {
        minLat: Math.min(...markers.map((m) => m.latitude)),
        minLon: Math.min(...markers.map((m) => m.longitude)),
        maxLat: Math.max(...markers.map((m) => m.latitude)),
        maxLon: Math.max(...markers.map((m) => m.longitude)),
      };
    }

    return { markers, bounds };
  }

  /**
   * Overview map data for the panoramic dashboard view: ONE marker per
   * unique locality (name + county + region) across all active trips —
   * presence localities within each trip's interval (respecting the
   * day/locality exclusions) plus manual-day localities, deduplicated.
   * Same aggregation rule as getTripMapData (§16/§6.3/§7.2), but scoped to
   * the whole set of active trips instead of a single trip.
   */
  async getTripsOverviewMapData(): Promise<{
    markers: MapMarkerDto[];
    bounds: BoundingBoxDto;
  }> {
    const result = await dbPool.query(
      `WITH active_trips AS (
         SELECT id, start_date, end_date FROM trips WHERE status = 'active'
       ),
       presence_rows AS (
         SELECT p.locality_id,
                l.name, l.county, l.region, l.country, l.locality_hash,
                p.photo_count,
                (SELECT MIN(ph.date_time_original)
                   FROM photos ph
                   JOIN geocoding_cache gc
                     ON gc.original_latitude = ph.original_latitude
                    AND gc.original_longitude = ph.original_longitude
                    AND gc.locality_id = p.locality_id
                  WHERE ph.date_time_original IS NOT NULL
                    AND ph.date_time_original::date = p.photo_date) AS first_photo_at,
                NULL::date AS first_day
         FROM presences p
         JOIN localities l ON l.id = p.locality_id
         JOIN active_trips t
           ON p.photo_date >= t.start_date AND p.photo_date <= t.end_date
         WHERE NOT EXISTS (
           SELECT 1 FROM trip_day_exclusions e
           WHERE e.trip_id = t.id
             AND e.day_date = p.photo_date
             AND (e.locality_key IS NULL
                  OR e.locality_key = lower(l.name) || '|' || COALESCE(l.county, '') || '|' || COALESCE(l.region, ''))
         )
       ),
       manual_rows AS (
         SELECT m.locality_id,
                l.name, l.county, l.region, l.country, l.locality_hash,
                0::int AS photo_count,
                NULL::timestamp AS first_photo_at,
                MIN(d.day_date) AS first_day
         FROM manual_trip_days d
         JOIN manual_trip_day_localities m ON m.day_id = d.id
         JOIN localities l ON l.id = m.locality_id
         JOIN active_trips t ON t.id = d.trip_id
         GROUP BY m.locality_id, l.name, l.county, l.region, l.country, l.locality_hash
       ),
       all_rows AS (
         SELECT * FROM presence_rows
         UNION ALL
         SELECT * FROM manual_rows
       ),
       aggregated AS (
         SELECT name,
                COALESCE(county, '') AS county_key,
                COALESCE(region, '') AS region_key,
                SUM(photo_count)::int AS photo_count,
                MIN(first_photo_at)   AS first_photo_at,
                MIN(first_day)        AS first_day
         FROM all_rows
         GROUP BY name, COALESCE(county, ''), COALESCE(region, '')
       ),
       representative AS (
         SELECT DISTINCT ON (r.name, COALESCE(r.county, ''), COALESCE(r.region, ''))
           r.locality_id, r.name, r.county, r.region, r.country, r.locality_hash,
           a.photo_count, a.first_photo_at, a.first_day
         FROM all_rows r
         JOIN aggregated a
           ON a.name = r.name
          AND a.county_key = COALESCE(r.county, '')
          AND a.region_key = COALESCE(r.region, '')
         WHERE r.locality_hash ~ '^-?[0-9]+\\.[0-9]+:-?[0-9]+\\.[0-9]+$'
         ORDER BY r.name, COALESCE(r.county, ''), COALESCE(r.region, ''),
                  r.first_photo_at NULLS LAST, r.locality_id
       )
       SELECT locality_id, name, county, region, country,
              photo_count, first_photo_at::text AS first_photo_at,
              split_part(locality_hash, ':', 1)::double precision AS latitude,
              split_part(locality_hash, ':', 2)::double precision AS longitude
       FROM representative
       ORDER BY COALESCE(first_photo_at, first_day::timestamp) NULLS LAST, name`,
    );

    const markers: MapMarkerDto[] = result.rows.map((r) => ({
      localityId: Number(r.locality_id),
      name: String(r.name),
      latitude: parseFloat(String(r.latitude)),
      longitude: parseFloat(String(r.longitude)),
      photoCount: Number(r.photo_count),
      firstPhotoAt: r.first_photo_at != null ? String(r.first_photo_at) : null,
      county: r.county != null ? String(r.county) : null,
      region: r.region != null ? String(r.region) : null,
      country: r.country != null ? String(r.country) : null,
    }));

    // Compute bounding box from markers
    let bounds: BoundingBoxDto;
    if (markers.length === 0) {
      // Default center (Italy-ish) when no markers exist
      bounds = { minLat: 37, minLon: 6, maxLat: 47.1, maxLon: 19 };
    } else {
      bounds = {
        minLat: Math.min(...markers.map((m) => m.latitude)),
        minLon: Math.min(...markers.map((m) => m.longitude)),
        maxLat: Math.max(...markers.map((m) => m.latitude)),
        maxLon: Math.max(...markers.map((m) => m.longitude)),
      };
    }

    return { markers, bounds };
  }
}

export default new TripsRepository();
