/**
 * Travelog MVP1 — Trips Repository
 *
 * All date values are naive ISO strings (YYYY-MM-DD) serialized in SQL
 * with to_char / cast with ::date: JS Date round-trips shift the calendar
 * day via UTC conversion (naive local time, requirements §5.2).
 */

import { db, pool as dbPool } from "../db/client.js";
import { trips } from "../db/schema.js";
import { eq, and, or, ilike, count, desc, asc, sql } from "drizzle-orm";
import type { PoolClient } from "pg";
import type { TripQueryOptions } from "../services/trips.service.js";

export interface TripDto {
  id: number;
  name: string;
  /** Naive ISO date, YYYY-MM-DD. */
  startDate: string;
  /** Naive ISO date, YYYY-MM-DD. */
  endDate: string;
  autoGenerated: boolean;
  status: string;
  createdAt: string;
}

export interface TripDayLocalityDto {
  localityId: number;
  name: string;
  county: string | null;
  region: string | null;
  country: string | null;
  photoCount: number;
}

export interface TripDayDto {
  /** Naive ISO date, YYYY-MM-DD. */
  date: string;
  /** True for days without photos ("Nessuna foto", §16). */
  noPhotos: boolean;
  localities: TripDayLocalityDto[];
}

const tripSelection = {
  id: trips.id,
  name: trips.name,
  startDate: sql<string>`to_char(${trips.startDate}, 'YYYY-MM-DD')`,
  endDate: sql<string>`to_char(${trips.endDate}, 'YYYY-MM-DD')`,
  autoGenerated: trips.autoGenerated,
  status: trips.status,
  createdAt: sql<string>`to_char(${trips.createdAt}, 'YYYY-MM-DD"T"HH24:MI:SS')`,
};

function mapTripRow(row: Record<string, unknown>): TripDto {
  return {
    id: Number(row.id),
    name: String(row.name),
    startDate: String(row.startDate),
    endDate: String(row.endDate),
    autoGenerated: Boolean(row.autoGenerated),
    status: String(row.status),
    createdAt: String(row.createdAt),
  };
}

class TripsRepository {
  async listTrips(options: TripQueryOptions): Promise<{
    items: TripDto[];
    page: number;
    pageSize: number;
    total: number;
  }> {
    const { status, search, sort, page, pageSize } = options;
    const offset = (page - 1) * pageSize;

    const conditions: ReturnType<typeof eq>[] = [];
    if (status) {
      conditions.push(eq(trips.status, status));
    }

    let finalCondition: ReturnType<typeof and> | undefined = undefined;
    if (conditions.length > 0 || search) {
      let searchCondition: ReturnType<typeof or> | undefined = undefined;
      if (search) {
        const pattern = `%${search}%`;
        searchCondition = or(
          ilike(trips.name, pattern),
          sql`EXTRACT(YEAR FROM ${trips.startDate})::TEXT LIKE ${pattern}`,
        );
      }

      if (conditions.length > 0 && searchCondition) {
        finalCondition = and(...conditions, searchCondition);
      } else if (conditions.length > 0) {
        finalCondition = and(...conditions);
      } else if (searchCondition) {
        finalCondition = searchCondition;
      }
    }

    const orderBy = sort === "startDateAsc" ? asc(trips.startDate) : desc(trips.startDate);

    const countResult = await db.select({ total: count() }).from(trips).where(finalCondition);
    const totalCount = countResult[0]?.total ?? 0;

    const rows = await db
      .select(tripSelection)
      .from(trips)
      .where(finalCondition)
      .orderBy(orderBy)
      .limit(pageSize)
      .offset(offset);

    return { items: rows.map(mapTripRow), page, pageSize, total: totalCount };
  }

  async getTrip(id: number): Promise<TripDto | null> {
    const rows = await db.select(tripSelection).from(trips).where(eq(trips.id, id));
    return rows.length > 0 ? mapTripRow(rows[0]) : null;
  }

  /**
   * Active trips overlapping the given inclusive interval. `excludeId`
   * removes one trip from the check (the trip being modified itself).
   */
  async findOverlappingTrips(
    startDate: string,
    endDate: string,
    excludeId?: number,
  ): Promise<TripDto[]> {
    const result = await dbPool.query(
      `SELECT id, name,
              to_char(start_date, 'YYYY-MM-DD') AS "startDate",
              to_char(end_date, 'YYYY-MM-DD') AS "endDate",
              auto_generated AS "autoGenerated", status,
              to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS "createdAt"
       FROM trips
       WHERE status = 'active'
         AND start_date <= $2::date
         AND end_date >= $1::date
         AND ($3::int IS NULL OR id <> $3::int)
       ORDER BY start_date`,
      [startDate, endDate, excludeId ?? null],
    );
    return result.rows.map(mapTripRow);
  }

  /**
   * Presences (day + locality) inside an inclusive date interval,
   * ordered chronologically: the building blocks of the trip detail
   * (requirements §16). The same administrative locality can exist as
   * several `localities` rows (one per rounded coordinate hash): the
   * aggregation by locality name happens in the service layer.
   */
  async getTripDays(startDate: string, endDate: string): Promise<TripDayDto[]> {
    const result = await dbPool.query(
      `SELECT to_char(p.photo_date, 'YYYY-MM-DD') AS day,
              l.id AS locality_id, l.name, l.county, l.region, l.country,
              p.photo_count
       FROM presences p
       JOIN localities l ON l.id = p.locality_id
       WHERE p.photo_date >= $1::date AND p.photo_date <= $2::date
       ORDER BY p.photo_date, p.photo_count DESC, l.name`,
      [startDate, endDate],
    );
    const days: TripDayDto[] = [];
    let currentDate: string | null = null;
    let currentLocalities = new Map<string, TripDayLocalityDto>();

    const flushDay = () => {
      if (currentDate === null) return;
      days.push({
        date: currentDate,
        noPhotos: false,
        localities: [...currentLocalities.values()],
      });
    };

    for (const r of result.rows) {
      const date = String(r.day);
      if (date !== currentDate) {
        flushDay();
        currentDate = date;
        currentLocalities = new Map();
      }
      // The same city can be present under several coordinate hashes:
      // aggregate by administrative name (§6.3/§7.2), summing the counts.
      const key = `${String(r.name).toLowerCase()}|${r.county ?? ""}|${r.region ?? ""}`;
      const existing = currentLocalities.get(key);
      if (existing) {
        existing.photoCount += Number(r.photo_count);
      } else {
        currentLocalities.set(key, {
          localityId: Number(r.locality_id),
          name: r.name,
          county: r.county ?? null,
          region: r.region ?? null,
          country: r.country ?? null,
          photoCount: Number(r.photo_count),
        });
      }
    }
    flushDay();
    return days;
  }

  /**
   * Insert a trip. Used by automatic generation (Phase 5) and by the
   * manual operations (Phase 6). Optional transaction client keeps the
   * whole operation atomic (technical design §64).
   */
  async insertTrip(
    input: {
      name: string;
      startDate: string;
      endDate: string;
      autoGenerated: boolean;
    },
    tx?: PoolClient,
  ): Promise<TripDto> {
    const client = tx ?? dbPool;
    const result = await client.query(
      `INSERT INTO trips (name, start_date, end_date, auto_generated, status)
       VALUES ($1, $2::date, $3::date, $4, 'active')
       RETURNING id, name,
                 to_char(start_date, 'YYYY-MM-DD') AS start_date,
                 to_char(end_date, 'YYYY-MM-DD') AS end_date,
                 auto_generated, status,
                 to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS created_at`,
      [input.name, input.startDate, input.endDate, input.autoGenerated],
    );
    const r = result.rows[0];
    return {
      id: Number(r.id),
      name: r.name,
      startDate: r.start_date,
      endDate: r.end_date,
      autoGenerated: r.auto_generated,
      status: r.status,
      createdAt: r.created_at,
    };
  }

  /**
   * Manual rename / date change (§13.1, §13.2). Undefined fields are
   * preserved.
   */
  async updateTrip(
    id: number,
    updates: { name?: string; startDate?: string; endDate?: string },
  ): Promise<TripDto | null> {
    const result = await dbPool.query(
      `UPDATE trips SET
         name       = COALESCE($2::text, name),
         start_date = COALESCE($3::date, start_date),
         end_date   = COALESCE($4::date, end_date),
         updated_at = now()
       WHERE id = $1::int
       RETURNING id, name,
                 to_char(start_date, 'YYYY-MM-DD') AS "startDate",
                 to_char(end_date, 'YYYY-MM-DD') AS "endDate",
                 auto_generated AS "autoGenerated", status,
                 to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS "createdAt"`,
      [id, updates.name ?? null, updates.startDate ?? null, updates.endDate ?? null],
    );
    return result.rows.length > 0 ? mapTripRow(result.rows[0]) : null;
  }

  /**
   * Physically delete a trip (explicit user operation: some generated
   * periods are not trips). Returns true when a row was deleted.
   */
  async deleteTrip(id: number): Promise<boolean> {
    const result = await dbPool.query(`DELETE FROM trips WHERE id = $1::int`, [id]);
    return result.rowCount !== null && result.rowCount > 0;
  }

  /**
   * Mark trips as superseded (split/merge keep the originals in the
   * database — requirements §13.3, §13.4).
   */
  async archiveTrips(ids: number[], tx?: PoolClient): Promise<void> {
    const client = tx ?? dbPool;
    await client.query(
      `UPDATE trips SET status = 'archived', updated_at = now() WHERE id = ANY($1::int[])`,
      [ids],
    );
  }

  /**
   * Active trips as naive date intervals (YYYY-MM-DD, serialized in SQL
   * so the values are independent from the server timezone).
   * Used by trip generation to protect existing trips (immutability).
   */
  async listActiveTripIntervals(): Promise<
    Array<{ id: number; startDate: string; endDate: string }>
  > {
    const rows = await db
      .select({
        id: trips.id,
        startDate: sql<string>`to_char(${trips.startDate}, 'YYYY-MM-DD')`,
        endDate: sql<string>`to_char(${trips.endDate}, 'YYYY-MM-DD')`,
      })
      .from(trips)
      .where(eq(trips.status, "active"));
    return rows.map((r) => ({ id: r.id, startDate: r.startDate, endDate: r.endDate }));
  }

  /**
   * Insert an auto-generated trip (Phase 5 trip generation).
   */
  async createAutoTrip(input: { name: string; startDate: string; endDate: string }) {
    return this.insertTrip({ ...input, autoGenerated: true });
  }
}

export default new TripsRepository();
