/**
 * Travelog MVP1 — External link button on the trips table rows
 *
 * Every trip row exposes an external-link button (right of the edit
 * buttons) that opens the trip detail card as a standalone, shareable
 * page (/trips/:id) in a new browser tab.
 */

import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";
import TripsTable from "../../components/TripsTable";
import type { Trip } from "../../api/client";

const fetchMock = vi.fn();
vi.stubGlobal("fetch", fetchMock);
vi.stubGlobal("open", vi.fn());

afterEach(() => {
  vi.mocked(window.open).mockReset();
});

const TRIP: Trip = {
  id: 1,
  name: "Vacanza in Toscana",
  startDate: "2025-08-10",
  endDate: "2025-08-13",
  autoGenerated: true,
  createdManually: false,
  status: "active",
  createdAt: "2025-09-01T10:00:00",
};

function renderTable(trip: Trip = TRIP): void {
  render(
    <TripsTable
      trips={[trip]}
      mergeMode={false}
      selectedIds={[]}
      selectedTripId={null}
      confirmDeleteId={null}
      detail={null}
      detailLoading={false}
      detailError={null}
      dialog={null}
      operating={false}
      onSelectTrip={() => undefined}
      onCloseDetail={() => undefined}
      onToggleSelected={() => undefined}
      onRename={() => undefined}
      onDates={() => undefined}
      onSplit={() => undefined}
      onDelete={() => undefined}
      onDeleteConfirm={() => undefined}
      onDeleteCancel={() => undefined}
      onDialogSubmit={() => undefined}
      onDialogCancel={() => undefined}
      deleting={false}
    />,
  );
}

describe("TripsTable — external link button", () => {
  it("renders the external-link button next to the edit buttons", () => {
    renderTable();
    expect(
      screen.getByRole("button", {
        name: "Apri la scheda dettaglio di Vacanza in Toscana in una nuova pagina",
      }),
    ).not.toBeNull();
  });

  it("opens /trips/:id in a new tab when clicked", () => {
    renderTable();
    fireEvent.click(
      screen.getByRole("button", {
        name: "Apri la scheda dettaglio di Vacanza in Toscana in una nuova pagina",
      }),
    );
    expect(window.open).toHaveBeenCalledWith("/trips/1", "_blank");
  });

  it("is also available for archived trips", () => {
    renderTable({ ...TRIP, id: 3, status: "archived" });
    fireEvent.click(
      screen.getByRole("button", {
        name: "Apri la scheda dettaglio di Vacanza in Toscana in una nuova pagina",
      }),
    );
    expect(window.open).toHaveBeenCalledWith("/trips/3", "_blank");
  });
});
