/**
 * Travelog — TripsDashboard (new UI, phase 4) tests
 *
 * Verifies the two-column layout: sidebar with the search field and the
 * accordion trip cards, and the full-height map of the selected trip.
 * Selection is delegated to the parent (`onSelectTrip`) and the card
 * actions reuse the per-trip context menu callbacks.
 *
 * Leaflet is mocked (same approach as trip-map.test.tsx) so only the map
 * mount is observable in jsdom.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, within, waitFor } from "@testing-library/react";
import type { ComponentProps } from "react";
import TripsDashboard from "../TripsDashboard";
import type { Trip, TripDetail, TripMapData, TripsOverviewMap } from "../../api/client";

const h = vi.hoisted(() => ({
  state: {
    mapCount: 0,
    maps: [] as any[],
    markers: [] as any[],
    heatLayers: [] as any[],
  },
}));

// Mock leaflet.heat plugin (used by HeatMap component)
vi.mock("leaflet.heat", () => ({}));

vi.mock("leaflet", () => {
  const state = h.state;

  class MapMock {
    zoom = 8;
    fitBounds = vi.fn();
    flyTo = vi.fn();
    /* HeatMap filters its points against the current viewport (§overview):
       it pads the bounds and tests each marker against them. */
    getBounds = () => ({
      pad: () => ({
        contains: ([lat, lng]: [number, number]) => lat >= 0 && lat <= 90 && lng >= 0 && lng <= 180,
      }),
    });
    closePopup = vi.fn();
    remove = vi.fn();
    addLayer = vi.fn();
    removeLayer = vi.fn();
    setView = vi.fn(() => this);
    getZoom = () => this.zoom;
    handlers: Record<string, (ev?: unknown) => void> = {};
    on(event: string, cb: (ev?: unknown) => void) {
      this.handlers[event] = cb;
      return this;
    }
    off(event: string) {
      delete this.handlers[event];
      return this;
    }
    constructor(_el: unknown) {
      void _el;
      state.mapCount += 1;
      state.maps.push(this);
    }
  }

  function makeMarker(latlng: unknown, opts: unknown) {
    const marker: any = {
      latlng,
      opts,
      popupOpen: false,
      handlers: {} as Record<string, () => void>,
      bindPopup: () => marker,
      on(event: string, cb: () => void) {
        marker.handlers[event] = cb;
        return marker;
      },
      openPopup() {
        marker.popupOpen = true;
        return marker;
      },
      closePopup() {
        marker.popupOpen = false;
        return marker;
      },
      getLatLng() {
        return marker.latlng;
      },
      /* Hover visual feedback swaps the icon (TripMap enlarge-on-hover). */
      setIcon(newIcon: unknown) {
        marker.opts = { ...marker.opts, icon: newIcon };
        return marker;
      },
    };
    state.markers.push(marker);
    return marker;
  }

  const chain = () => {
    const obj: any = {
      addTo: () => obj,
      remove: () => {},
      on: () => obj,
      addLayer: () => {},
      clearLayers: () => {},
    };
    return obj;
  };

  return {
    default: {
      map: (_el: unknown) => new MapMock(_el),
      tileLayer: () => chain(),
      layerGroup: () => chain(),
      marker: makeMarker,
      divIcon: (opts: unknown) => opts,
      polyline: () => chain(),
      latLngBounds: (latlngs: unknown) => ({ latlngs }),
      control: {
        layers: () => chain(),
        zoom: () => chain(),
      },
      /* HeatMap (overview) records its points: [lat, lng, intensity]. */
      heatLayer: (latlngs: unknown, opts: unknown) => {
        const layer: any = {
          latlngs,
          opts,
          addTo: () => layer,
          setLatLngs(next: unknown) {
            layer.latlngs = next;
            return layer;
          },
          setOptions(next: Record<string, unknown>) {
            layer.opts = { ...layer.opts, ...next };
            return layer;
          },
        };
        state.heatLayers.push(layer);
        return layer;
      },
      Control: class {
        onAdd: (() => HTMLElement) | null = null;
        constructor(_opts: unknown) {
          void _opts;
        }
        addTo() {
          this.onAdd?.();
          return this;
        }
      },
      DomUtil: {
        create: (tag: string, cls: string) => {
          const el = document.createElement(tag);
          el.className = cls;
          return el;
        },
      },
      DomEvent: {
        disableClickPropagation: vi.fn(),
        disableScrollPropagation: vi.fn(),
      },
    },
  };
});

function makeTrip(overrides: Partial<Trip> = {}): Trip {
  return {
    id: 1,
    name: "Lozon",
    startDate: "2026-07-03",
    endDate: "2026-07-31",
    autoGenerated: true,
    createdManually: false,
    status: "active",
    createdAt: "2026-08-01T10:00:00",
    photoCount: 42,
    regions: ["Valle d'Aosta"],
    ...overrides,
  };
}

const TRIPS: Trip[] = [
  makeTrip(),
  makeTrip({
    id: 2,
    name: "Sicilia",
    startDate: "2026-08-01",
    endDate: "2026-08-10",
    photoCount: 7,
    regions: ["Sicilia"],
  }),
];

const MAP_DATA: TripMapData = {
  id: 1,
  name: "Lozon",
  startDate: "2026-07-03",
  endDate: "2026-07-31",
  bounds: { minLat: 0, minLon: 0, maxLat: 1, maxLon: 1 },
  markers: [
    {
      localityId: 10,
      name: "Lozon",
      latitude: 45.7,
      longitude: 7.6,
      photoCount: 5,
      firstPhotoAt: "2026-07-03T10:00:00",
      county: "Aosta",
      region: "Valle d'Aosta",
      country: "Italy",
      countyColor: "#2563EB",
    },
  ],
  countyColors: { Aosta: "#2563EB" },
};

/** Panoramic overview map (all active trips): one marker per locality. */
const OVERVIEW_MAP: TripsOverviewMap = {
  bounds: { minLat: 37, minLon: 7, maxLat: 46, maxLon: 13 },
  markers: [
    {
      localityId: 10,
      name: "Lozon",
      latitude: 45.7,
      longitude: 7.6,
      photoCount: 5,
      firstPhotoAt: "2026-07-03T10:00:00",
      county: "Aosta",
      region: "Valle d'Aosta",
      country: "Italy",
      countyColor: "#2563EB",
    },
    {
      localityId: 20,
      name: "Trapani",
      latitude: 38.0,
      longitude: 12.5,
      photoCount: 7,
      firstPhotoAt: "2026-08-01T10:00:00",
      county: "Trapani",
      region: "Sicilia",
      country: "Italy",
      countyColor: "#EA4335",
    },
  ],
  countyColors: { Aosta: "#2563EB", Trapani: "#EA4335" },
  computedAt: "2026-07-03T10:00:00",
};

/** Detail of trip 1: one day with the locality 10 (matches MAP_DATA). */
const DETAIL: TripDetail = {
  ...TRIPS[0],
  days: [
    {
      date: "2026-07-03",
      noPhotos: false,
      manual: false,
      localities: [
        {
          localityId: 10,
          name: "Lozon",
          county: "Aosta",
          region: "Valle d'Aosta",
          country: "Italy",
          photoCount: 5,
          manual: false,
        },
      ],
    },
  ],
};

function baseProps(extra: Partial<ComponentProps<typeof TripsDashboard>> = {}) {
  return {
    trips: TRIPS,
    loading: false,
    error: null as string | null,
    selectedTripId: null as number | null,
    onSelectTrip: vi.fn(),
    detailLoading: false,
    detailError: null as string | null,
    mapData: null as TripMapData | null,
    onRename: vi.fn(),
    onEditDates: vi.fn(),
    onSplit: vi.fn(),
    onDelete: vi.fn(),
    ...extra,
  };
}

beforeEach(() => {
  h.state.mapCount = 0;
  h.state.maps = [];
  h.state.markers = [];
  h.state.heatLayers = [];
});

describe("TripsDashboard (new UI, phase 4)", () => {
  it("renders the sidebar with one card per trip", () => {
    render(<TripsDashboard {...baseProps()} />);

    expect(screen.getByText("I Miei Viaggi")).toBeTruthy();
    expect(screen.getByText("Lozon")).toBeTruthy();
    expect(screen.getAllByText("Sicilia").length).toBeGreaterThan(0);
    expect(screen.getByText("3 Lug - 31 Lug 2026 · 29 gg")).toBeTruthy();
  });

  it("reports the clicked card through onSelectTrip", () => {
    const onSelectTrip = vi.fn();
    render(<TripsDashboard {...baseProps({ onSelectTrip })} />);

    fireEvent.click(screen.getByRole("button", { name: /^Sicilia/ }));
    expect(onSelectTrip).toHaveBeenCalledWith(2);
  });

  it("expands only the selected card and shows the detail loading inside it", () => {
    const { container } = render(
      <TripsDashboard {...baseProps({ selectedTripId: 1, detailLoading: true })} />,
    );

    const first = container.querySelector('[data-trip-id="1"]') as HTMLElement;
    const second = container.querySelector('[data-trip-id="2"]') as HTMLElement;

    expect(within(first).getByRole("status")).toBeTruthy();
    expect(within(second).queryByRole("status")).toBeNull();
    expect(
      within(first)
        .getByRole("button", { name: /^Lozon/ })
        .getAttribute("aria-expanded"),
    ).toBe("true");
    expect(
      within(second)
        .getByRole("button", { name: /^Sicilia/ })
        .getAttribute("aria-expanded"),
    ).toBe("false");
    expect(first.classList.contains("trip-card--active")).toBe(true);
  });

  it("shows the detail error inside the expanded card", () => {
    render(<TripsDashboard {...baseProps({ selectedTripId: 1, detailError: "boom" })} />);
    expect(screen.getByRole("alert").textContent).toContain("boom");
  });

  it("renders the full-height map when the selected trip has map data", () => {
    const { container } = render(
      <TripsDashboard {...baseProps({ selectedTripId: 1, mapData: MAP_DATA })} />,
    );

    expect(h.state.mapCount).toBe(1);
    expect(container.querySelector(".trip-map-container--full")).toBeTruthy();
  });

  it("renders the panoramic heatmap when no trip is selected", () => {
    const { container } = render(
      <TripsDashboard {...baseProps({ overviewMapData: OVERVIEW_MAP })} />,
    );

    // The overview is a heatmap of photo density (not the waypoint pins):
    // no "select a trip" hint, one heat point per locality, no pins.
    expect(screen.queryByText("Seleziona un viaggio per visualizzarlo sulla mappa.")).toBeNull();
    expect(h.state.mapCount).toBe(1);
    expect(h.state.heatLayers).toHaveLength(1);
    expect(h.state.markers).toHaveLength(0);

    // Intensity normalized 0..1 against the busiest locality (7 photos):
    // Lozon (5 photos) gets 5/7, Trapani (7 photos) gets full intensity.
    const heat = h.state.heatLayers[0];
    expect(heat.latlngs).toEqual([
      [45.7, 7.6, 5 / 7],
      [38, 12.5, 1],
    ]);

    // maxZoom is synced to the CURRENT zoom (8 in the mock), not a fixed
    // value: the plugin scales intensity by 1/2^(maxZoom - zoom), so a
    // fixed maxZoom would make the layer invisible at the fit zoom.
    expect(heat.opts.maxZoom).toBe(8);
    expect(heat.opts.max).toBe(1);

    // The blob size starts at the user baseline (radius 12 / blur 10 on
    // the fit zoom) and is RESCALED on zoom: leaflet.heat draws in fixed
    // pixels, so a constant size merges distant localities into one blob
    // when zoomed out.
    expect(heat.opts.radius).toBe(12);
    expect(heat.opts.blur).toBe(10);

    // Zooming re-points maxZoom to the new zoom (intensity factor stays 1,
    // heat points keep their normalized strength) and rescales the blob
    // size: zoom 10 → radius round((10-2)*2) = 16,
    // blur round(16*10/26) = 6 (blur ≈ 10/26 of the radius).
    const map = h.state.maps[0];
    map.zoom = 10;
    map.handlers["zoomend"]();
    expect(heat.opts.maxZoom).toBe(10);
    expect(heat.opts.radius).toBe(16);
    expect(heat.opts.blur).toBe(6);

    // Tight fit: no integer-zoom rounding (zoomSnap: 0 on the map) and a
    // raised zoom cap, so the frame is the minimum necessary to contain
    // all localities without artificial widening.
    expect(map.fitBounds).toHaveBeenCalledWith(
      expect.anything(),
      expect.objectContaining({ maxZoom: 18 }),
    );

    // No region legend inside the map panel: the heatmap shows only the
    // heat layer (the county legend belongs to the trip map only).
    const mapPanel = container.querySelector('[aria-label="Mappa viaggi"]') as HTMLElement;
    expect(within(mapPanel).queryByText(/regione|Aosta|Trapani/)).toBeNull();
    expect(container.querySelector(".trip-map-container--full")).toBeTruthy();
  });

  it("keeps the selected trip map visible after the trip is closed (mapData retained)", () => {
    // Closing a trip only clears the selection on the parent side: the
    // dashboard keeps rendering the last trip map (marker + track + legend)
    // until another trip is selected — the overview heatmap must NOT
    // come back in between.
    const { container } = render(
      <TripsDashboard
        {...baseProps({
          selectedTripId: null,
          mapData: MAP_DATA,
          overviewMapData: OVERVIEW_MAP,
        })}
      />,
    );

    expect(h.state.mapCount).toBe(1);
    expect(h.state.heatLayers).toHaveLength(0); // heatmap hidden
    expect(h.state.markers).toHaveLength(1); // trip pins still visible
    expect(container.querySelector(".trip-map-container--full")).toBeTruthy();
  });

  it("shows a hint instead of the map when no trip is selected or no map is available", () => {
    const { rerender } = render(<TripsDashboard {...baseProps()} />);
    expect(screen.getByText("Seleziona un viaggio per visualizzarlo sulla mappa.")).toBeTruthy();
    expect(h.state.mapCount).toBe(0);

    rerender(<TripsDashboard {...baseProps({ selectedTripId: 1, mapData: null })} />);
    expect(screen.getByText("Nessuna mappa disponibile per questo viaggio.")).toBeTruthy();
    expect(h.state.mapCount).toBe(0);
  });

  it("routes the card context-menu actions to the matching trip", () => {
    const onRename = vi.fn();
    const onEditDates = vi.fn();
    const onSplit = vi.fn();
    const onDelete = vi.fn();
    render(<TripsDashboard {...baseProps({ onRename, onEditDates, onSplit, onDelete })} />);

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Sicilia" }));
    fireEvent.click(screen.getByRole("menuitem", { name: /Rinomina/ }));
    expect(onRename).toHaveBeenCalledWith(TRIPS[1]);

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Sicilia" }));
    fireEvent.click(screen.getByRole("menuitem", { name: /Modifica date/ }));
    expect(onEditDates).toHaveBeenCalledWith(TRIPS[1]);

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Sicilia" }));
    fireEvent.click(screen.getByRole("menuitem", { name: /Dividi viaggio/ }));
    expect(onSplit).toHaveBeenCalledWith(TRIPS[1]);

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Sicilia" }));
    fireEvent.click(screen.getByRole("menuitem", { name: /Elimina/ }));
    expect(onDelete).toHaveBeenCalledWith(TRIPS[1]);
  });

  it("shows the empty state and the list error", () => {
    const { rerender } = render(<TripsDashboard {...baseProps({ trips: [] })} />);
    expect(screen.getByText("Nessun viaggio trovato.")).toBeTruthy();

    rerender(<TripsDashboard {...baseProps({ error: "Errore di rete" })} />);
    expect(screen.getByRole("alert").textContent).toContain("Errore di rete");
  });

  it("renders the trip timeline inside the expanded card", () => {
    render(<TripsDashboard {...baseProps({ selectedTripId: 1, detail: DETAIL })} />);

    expect(screen.getByText("03/07/2026")).toBeTruthy();
    expect(screen.getByText(/5 foto/)).toBeTruthy();
  });

  it("keeps the timeline and the map in sync (UI §3.1)", () => {
    const { container } = render(
      <TripsDashboard {...baseProps({ selectedTripId: 1, detail: DETAIL, mapData: MAP_DATA })} />,
    );

    const row = () => container.querySelector('[data-locality-id="10"]') as HTMLElement;
    const map = h.state.maps[0];
    const marker = h.state.markers[0];
    const normalIcon = marker.opts.icon;

    // Hovering a timeline row only enlarges the matching pin: no popup and
    // no fly-to (hover must never move the map view).
    fireEvent.mouseEnter(row());
    expect(marker.popupOpen).toBe(false);
    expect(map.flyTo).not.toHaveBeenCalled();
    expect(marker.opts.icon).not.toBe(normalIcon);
    expect(row().classList.contains("locality-card--active")).toBe(true);

    // Leaving the row restores the normal pin and clears the highlight.
    fireEvent.mouseLeave(row());
    expect(marker.opts.icon).toBe(normalIcon);
    expect(row().classList.contains("locality-card--active")).toBe(false);
  });

  it("keeps the search field and the global action menu out of the dashboard (§1.1)", () => {
    render(<TripsDashboard {...baseProps()} />);

    // Both live in the application top bar, rendered by the page.
    expect(screen.queryByLabelText("Cerca viaggi")).toBeNull();
    expect(screen.queryByRole("button", { name: "Azioni" })).toBeNull();
  });

  it("keeps the expanded card read-only without onReplaceDays", () => {
    render(<TripsDashboard {...baseProps({ selectedTripId: 1, detail: DETAIL })} />);

    expect(screen.queryByRole("menuitem", { name: "Modifica viaggio" })).toBeNull();
    expect(screen.queryByRole("button", { name: /Elimina il giorno/ })).toBeNull();
  });

  it("hides the Modifica viaggio entry on archived trips", () => {
    const archivedTrips: Trip[] = [makeTrip({ status: "archived" }), TRIPS[1]];
    render(
      <TripsDashboard
        {...baseProps({
          trips: archivedTrips,
          selectedTripId: 1,
          detail: DETAIL,
          onReplaceDays: vi.fn(),
        })}
      />,
    );

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Lozon" }));
    expect(screen.queryByRole("menuitem", { name: "Modifica viaggio" })).toBeNull();
  });

  it('enables the inline day/locality editing from the "Modifica viaggio" menu voice (§51)', async () => {
    const onReplaceDays = vi.fn().mockResolvedValue(undefined);
    render(<TripsDashboard {...baseProps({ selectedTripId: 1, detail: DETAIL, onReplaceDays })} />);

    // Read-only until the context-menu voice is chosen.
    expect(screen.queryByRole("button", { name: /Elimina la località/ })).toBeNull();

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Lozon" }));
    fireEvent.click(screen.getByRole("menuitem", { name: "Modifica viaggio" }));

    // Deleting the only locality of the day persists the day without it,
    // reporting the trip id to the parent.
    fireEvent.click(
      screen.getByRole("button", { name: "Elimina la località Lozon del giorno 03/07/2026" }),
    );
    await waitFor(() => {
      expect(onReplaceDays).toHaveBeenCalledTimes(1);
    });
    expect(onReplaceDays).toHaveBeenCalledWith(1, [{ date: "2026-07-03" }]);
  });
});

describe("TripsDashboard — year grouping accordion", () => {
  const MULTI_YEAR_TRIPS: Trip[] = [
    makeTrip({ id: 4, name: "Viaggio 2026", startDate: "2026-07-03", endDate: "2026-07-31" }),
    makeTrip({ id: 2, name: "2025 uno", startDate: "2025-03-01", endDate: "2025-03-05" }),
    makeTrip({ id: 3, name: "2025 due", startDate: "2025-08-01", endDate: "2025-08-10" }),
    makeTrip({ id: 1, name: "Vecchio 2024", startDate: "2024-07-03", endDate: "2024-07-10" }),
  ];

  /** Card of the trip with the given id (present only while its year is open). */
  const card = (container: HTMLElement, tripId: number): Element | null =>
    container.querySelector(`[data-trip-id="${tripId}"]`);

  it("groups the trips by start-date year in reverse chronological order with a per-year count", () => {
    const { container } = render(<TripsDashboard {...baseProps({ trips: MULTI_YEAR_TRIPS })} />);

    const headers = screen.getAllByRole("button", { name: /Viaggi \d{4}/ });
    expect(headers.map((el) => el.textContent!.replace(/\s+/g, " ").trim())).toEqual([
      "20261 viaggio",
      "20252 viaggi",
      "20241 viaggio",
    ]);
    // Cards of every year are visible while all groups are open.
    expect(card(container, 1)).not.toBeNull();
    expect(card(container, 2)).not.toBeNull();
    expect(card(container, 3)).not.toBeNull();
    expect(card(container, 4)).not.toBeNull();
  });

  it("closes only the clicked year and keeps the others open", () => {
    const { container } = render(<TripsDashboard {...baseProps({ trips: MULTI_YEAR_TRIPS })} />);

    fireEvent.click(screen.getByRole("button", { name: "Viaggi 2025" }));

    // Both 2025 cards are hidden; other years keep their cards.
    expect(card(container, 2)).toBeNull();
    expect(card(container, 3)).toBeNull();
    expect(card(container, 1)).not.toBeNull();
    expect(card(container, 4)).not.toBeNull();
    expect(screen.getByRole("button", { name: "Viaggi 2025" }).getAttribute("aria-expanded")).toBe(
      "false",
    );
  });

  it("allows closing multiple years at once and reopening them independently", () => {
    const { container } = render(<TripsDashboard {...baseProps({ trips: MULTI_YEAR_TRIPS })} />);

    fireEvent.click(screen.getByRole("button", { name: "Viaggi 2026" }));
    fireEvent.click(screen.getByRole("button", { name: "Viaggi 2024" }));
    expect(card(container, 1)).toBeNull();
    expect(card(container, 4)).toBeNull();
    expect(card(container, 2)).not.toBeNull();

    // Reopening 2024 does not reopen 2026.
    fireEvent.click(screen.getByRole("button", { name: "Viaggi 2024" }));
    expect(card(container, 1)).not.toBeNull();
    expect(card(container, 4)).toBeNull();
  });

  it("expands and collapses all years from the sidebar header commands", () => {
    const { container } = render(<TripsDashboard {...baseProps({ trips: MULTI_YEAR_TRIPS })} />);

    fireEvent.click(screen.getByRole("button", { name: "Comprimi tutti gli anni" }));
    expect(card(container, 1)).toBeNull();
    expect(card(container, 2)).toBeNull();
    expect(card(container, 3)).toBeNull();
    expect(card(container, 4)).toBeNull();

    fireEvent.click(screen.getByRole("button", { name: "Espandi tutti gli anni" }));
    expect(card(container, 1)).not.toBeNull();
    expect(card(container, 2)).not.toBeNull();
    expect(card(container, 3)).not.toBeNull();
    expect(card(container, 4)).not.toBeNull();
  });
});
