/**
 * Travelog MVP1 — Trip detail inline day editing tests
 *
 * Manual trips (createdManually) are edited inline in the trip detail:
 * the day trash deletes the whole day, the locality trash removes a
 * single locality and "Aggiungi località" opens the Geoapify search
 * inside the day. Every change persists the full day list through the
 * onReplaceDays callback (PUT /trips/{tripId}/days).
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, screen, waitFor, fireEvent } from "@testing-library/react";
import TripDetailPanel from "../../components/TripDetailPanel";
import { autocompleteLocalities, resolveLocality } from "../../api/exclusion-zones";
import type { TripDetail } from "../../api/client";

vi.mock("../../api/exclusion-zones", () => ({
  autocompleteLocalities: vi.fn(),
  resolveLocality: vi.fn(),
}));

const autocompleteMock = vi.mocked(autocompleteLocalities);
const resolveMock = vi.mocked(resolveLocality);

const DETAIL: TripDetail = {
  id: 2,
  name: "Prova",
  startDate: "2025-08-10",
  endDate: "2025-08-11",
  autoGenerated: false,
  createdManually: true,
  status: "active",
  createdAt: "2025-09-01T10:00:00",
  days: [
    {
      date: "2025-08-10",
      noPhotos: false,
      manual: true,
      localities: [
        {
          localityId: 7,
          name: "Siena",
          county: "Siena",
          region: "Toscana",
          country: "Italy",
          photoCount: 0,
          manual: true,
        },
        {
          localityId: 8,
          name: "Firenze",
          county: null,
          region: null,
          country: null,
          photoCount: 0,
          manual: true,
        },
      ],
    },
    { date: "2025-08-11", noPhotos: false, manual: true, localities: [] },
  ],
};

const SUGGESTION = {
  placeId: "place-verona",
  name: "Verona",
  countryCode: "IT",
  county: "Verona",
  region: "Veneto",
  country: "Italy",
  resultType: "city",
};

const RESOLVED = {
  id: 9,
  localityHash: "45.43:10.99",
  source: "geoapify-autocomplete",
  countryCode: "IT",
  name: "Verona",
  adminLevel: 8,
  county: "Verona",
  region: "Veneto",
  country: "Italy",
};

beforeEach(() => {
  autocompleteMock.mockResolvedValue([SUGGESTION]);
  resolveMock.mockResolvedValue(RESOLVED);
});

afterEach(() => {
  vi.clearAllMocks();
});

describe("TripDetailPanel — inline day editing (manual trips)", () => {
  /** Enter the edit mode (the "Modifica" toggle in the header). */
  function startEditing(): void {
    fireEvent.click(screen.getByRole("button", { name: "Modifica" }));
  }

  it("deletes a locality and persists the remaining days", async () => {
    const onReplaceDays = vi.fn().mockResolvedValue(undefined);
    render(<TripDetailPanel detail={DETAIL} onReplaceDays={onReplaceDays} />);
    startEditing();

    fireEvent.click(
      screen.getByRole("button", { name: "Elimina la località Siena del giorno 10/08/2025" }),
    );

    await waitFor(() => {
      expect(onReplaceDays).toHaveBeenCalledTimes(1);
    });
    expect(onReplaceDays).toHaveBeenCalledWith([
      { date: "2025-08-10", localityIds: [8] },
      { date: "2025-08-11" },
    ]);
  });

  it("deletes a whole day and persists the remaining days", async () => {
    const onReplaceDays = vi.fn().mockResolvedValue(undefined);
    render(<TripDetailPanel detail={DETAIL} onReplaceDays={onReplaceDays} />);
    startEditing();

    fireEvent.click(screen.getByRole("button", { name: "Elimina il giorno 11/08/2025" }));

    await waitFor(() => {
      expect(onReplaceDays).toHaveBeenCalledTimes(1);
    });
    expect(onReplaceDays).toHaveBeenCalledWith([{ date: "2025-08-10", localityIds: [7, 8] }]);
  });

  it("disables the day trash when only one day is left", () => {
    const onReplaceDays = vi.fn();
    const single = { ...DETAIL, days: [DETAIL.days[0]] };
    render(<TripDetailPanel detail={single} onReplaceDays={onReplaceDays} />);
    startEditing();

    const trash = screen.getByRole("button", { name: "Elimina il giorno 10/08/2025" });
    expect((trash as HTMLButtonElement).disabled).toBe(true);
    expect(onReplaceDays).not.toHaveBeenCalled();
  });

  it("'Aggiungi località' opens the search inside the day and adds the resolved locality", async () => {
    const onReplaceDays = vi.fn().mockResolvedValue(undefined);
    render(<TripDetailPanel detail={DETAIL} onReplaceDays={onReplaceDays} />);
    startEditing();

    // Open the search on the empty day.
    fireEvent.click(screen.getByRole("button", { name: "Aggiungi località al giorno 11/08/2025" }));
    const input = screen.getByLabelText("Località visitate il 11/08/2025");
    expect(input).not.toBeNull();

    // The debounced autocomplete resolves the query and lists the place.
    fireEvent.change(input, { target: { value: "vero" } });
    await waitFor(() => {
      expect(screen.getByText("Verona")).not.toBeNull();
    });
    expect(autocompleteMock).toHaveBeenCalledWith("vero");

    fireEvent.click(screen.getByRole("button", { name: "Aggiungi" }));

    await waitFor(() => {
      expect(onReplaceDays).toHaveBeenCalledWith([
        { date: "2025-08-10", localityIds: [7, 8] },
        { date: "2025-08-11", localityIds: [9] },
      ]);
    });
    // On success the search closes.
    await waitFor(() => {
      expect(screen.queryByLabelText("Località visitate il 11/08/2025")).toBeNull();
    });
  });

  it("shows a failed save as an in-panel error", async () => {
    const onReplaceDays = vi.fn().mockRejectedValue(new Error("Boom"));
    render(<TripDetailPanel detail={DETAIL} onReplaceDays={onReplaceDays} />);
    startEditing();

    fireEvent.click(
      screen.getByRole("button", { name: "Elimina la località Firenze del giorno 10/08/2025" }),
    );
    await waitFor(() => {
      expect(screen.getByText("Boom")).not.toBeNull();
    });
  });

  it("renders read-only days without edit affordances when no callback is provided", () => {
    render(<TripDetailPanel detail={DETAIL} />);
    expect(screen.queryByRole("button", { name: /Aggiungi località al giorno/ })).toBeNull();
    expect(screen.queryByRole("button", { name: /Elimina il giorno/ })).toBeNull();
    expect(screen.queryByRole("button", { name: /Elimina la località/ })).toBeNull();
    // The days are still rendered.
    expect(screen.getByText("Siena")).not.toBeNull();
    expect(screen.getByText("Giorno senza località")).not.toBeNull();
  });
});
