/**
 * Travelog MVP1 — External link on the trip cards
 *
 * Every trip card exposes an external-link button (next to the context
 * menu) that opens the trip detail card as a standalone, shareable page
 * (/trips/:id) in a new browser tab. The button appears only when the
 * parent provides the `onOpenDetail` handler.
 */

import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";
import TripCard from "../TripCard";
import type { Trip } from "../../api/client";

vi.stubGlobal("open", vi.fn());

afterEach(() => {
  vi.mocked(window.open).mockReset();
});

const TRIP: Trip = {
  id: 1,
  name: "Vacanza in Toscana",
  startDate: "2025-08-10",
  endDate: "2025-08-13",
  autoGenerated: true,
  createdManually: false,
  status: "active",
  createdAt: "2025-09-01T10:00:00",
};

const LINK_NAME = "Apri la scheda dettaglio di Vacanza in Toscana in una nuova pagina";

function renderCard(trip: Trip = TRIP): void {
  render(
    <TripCard
      trip={trip}
      expanded={false}
      onToggle={() => undefined}
      onRename={() => undefined}
      onEditDates={() => undefined}
      onSplit={() => undefined}
      onDelete={() => undefined}
      onOpenDetail={(t) => window.open(`/trips/${t.id}`, "_blank")}
    />,
  );
}

describe("TripCard — external link button", () => {
  it("renders the external-link button next to the context menu", () => {
    renderCard();
    expect(screen.getByRole("button", { name: LINK_NAME })).not.toBeNull();
  });

  it("opens /trips/:id in a new tab when clicked", () => {
    renderCard();
    fireEvent.click(screen.getByRole("button", { name: LINK_NAME }));
    expect(window.open).toHaveBeenCalledWith("/trips/1", "_blank");
  });

  it("is also available for archived trips", () => {
    renderCard({ ...TRIP, id: 3, status: "archived" });
    fireEvent.click(screen.getByRole("button", { name: LINK_NAME }));
    expect(window.open).toHaveBeenCalledWith("/trips/3", "_blank");
  });

  it("does not expand the card when clicked", () => {
    const onToggle = vi.fn();
    render(
      <TripCard
        trip={TRIP}
        expanded={false}
        onToggle={onToggle}
        onRename={() => undefined}
        onEditDates={() => undefined}
        onSplit={() => undefined}
        onDelete={() => undefined}
        onOpenDetail={(t) => window.open(`/trips/${t.id}`, "_blank")}
      />,
    );

    fireEvent.click(screen.getByRole("button", { name: LINK_NAME }));
    expect(onToggle).not.toHaveBeenCalled();
  });

  it("is not rendered without an onOpenDetail handler", () => {
    render(
      <TripCard
        trip={TRIP}
        expanded={false}
        onToggle={() => undefined}
        onRename={() => undefined}
        onEditDates={() => undefined}
        onSplit={() => undefined}
        onDelete={() => undefined}
      />,
    );

    expect(screen.queryByRole("button", { name: LINK_NAME })).toBeNull();
  });
});
