/**
 * Travelog MVP1 — Trips UI and exclusion zones tests (Phase 8)
 *
 * Verifies the trips page (list, detail with "Nessuna foto" days,
 * merge selection flow) and the exclusion zones panel against mocked
 * API responses.
 */

import { describe, it, expect, vi, afterEach } from "vitest";
import { useState } from "react";
import { render, screen, waitFor, fireEvent } from "@testing-library/react";
import TripsPage from "../../pages/TripsPage";
import ExclusionZonesPanel from "../../components/ExclusionZonesPanel";
import { useAutoDismiss } from "../../hooks/useAutoDismiss";

const fetchMock = vi.fn();
vi.stubGlobal("fetch", fetchMock);

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status });
}

afterEach(() => {
  fetchMock.mockReset();
});

const TRIPS = {
  items: [
    {
      id: 1,
      name: "Vacanza in Toscana",
      startDate: "2025-08-10",
      endDate: "2025-08-13",
      autoGenerated: true,
      status: "active",
      createdAt: "2025-09-01T10:00:00",
    },
    {
      id: 2,
      name: "Weekend a Roma",
      startDate: "2025-09-05",
      endDate: "2025-09-06",
      autoGenerated: false,
      status: "active",
      createdAt: "2025-09-10T10:00:00",
    },
  ],
  page: 1,
  pageSize: 20,
  total: 2,
};

const TRIP_DETAIL = {
  ...TRIPS.items[0],
  days: [
    {
      date: "2025-08-10",
      noPhotos: false,
      localities: [
        {
          localityId: 7,
          name: "Siena",
          county: "Siena",
          region: "Toscana",
          country: "Italy",
          photoCount: 12,
        },
      ],
    },
    { date: "2025-08-11", noPhotos: true, localities: [] },
    {
      date: "2025-08-12",
      noPhotos: false,
      localities: [
        {
          localityId: 8,
          name: "Firenze",
          county: "Firenze",
          region: "Toscana",
          country: "Italy",
          photoCount: 3,
        },
      ],
    },
    {
      date: "2025-08-13",
      noPhotos: false,
      localities: [
        {
          localityId: 8,
          name: "Firenze",
          county: "Firenze",
          region: "Toscana",
          country: "Italy",
          photoCount: 5,
        },
      ],
    },
  ],
};

/** Route mock fetch calls to the fake backend. */
function mockApi(): void {
  fetchMock.mockImplementation(async (input: RequestInfo | URL) => {
    const url = String(input);
    if (/^\/api\/trips\/1(\?|$)/.test(url)) return jsonResponse(TRIP_DETAIL);
    if (/^\/api\/trips\?/.test(url) || url === "/api/trips") return jsonResponse(TRIPS);
    if (url.startsWith("/api/operations")) {
      return jsonResponse({ items: [], page: 1, pageSize: 20, total: 0 });
    }
    throw new Error(`Unhandled fetch: ${url}`);
  });
}

describe("TripsPage", () => {
  it("renders the trip list with year, month, dates and duration (§15)", async () => {
    mockApi();
    render(<TripsPage />);

    await waitFor(() => {
      expect(screen.getByText("Vacanza in Toscana")).not.toBeNull();
    });
    expect(screen.getByText("Weekend a Roma")).not.toBeNull();
    expect(screen.getByText("10/08/2025")).not.toBeNull();
    expect(screen.getByText("13/08/2025")).not.toBeNull();
    expect(screen.getByText("4 gg")).not.toBeNull();
    expect(screen.getAllByText("agosto").length).toBeGreaterThan(0);
    expect(screen.getAllByText("2025").length).toBeGreaterThan(0);
  });

  it("offers the explicit recalculation command on the trips page", async () => {
    fetchMock.mockImplementation(async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input);
      if (url === "/api/settings" && init?.method === "POST") {
        return jsonResponse({ status: "ACCEPTED" });
      }
      if (/^\/api\/trips\?/.test(url) || url === "/api/trips") return jsonResponse(TRIPS);
      if (url.startsWith("/api/operations")) {
        return jsonResponse({ items: [], page: 1, pageSize: 20, total: 0 });
      }
      throw new Error(`Unhandled fetch: ${url}`);
    });

    render(<TripsPage />);

    await waitFor(() => {
      expect(screen.getByText("Vacanza in Toscana")).not.toBeNull();
    });

    fireEvent.click(screen.getByRole("button", { name: "Ricalcola" }));

    await waitFor(() => {
      expect(screen.getByText(/Ricalcolo richiesto/)).not.toBeNull();
    });
  });

  it("opens the trip detail with day/locality chronology and 'Nessuna foto' gaps (§16)", async () => {
    mockApi();

    render(<TripsPage />);

    await waitFor(() => {
      expect(screen.getByText("Vacanza in Toscana")).not.toBeNull();
    });
    fireEvent.click(screen.getByText("Vacanza in Toscana"));

    await waitFor(() => {
      expect(screen.getByText("Nessuna foto")).not.toBeNull();
    });
    expect(screen.getAllByText(/Siena/).length).toBeGreaterThan(0);
    expect(screen.getByText(/12 foto/)).not.toBeNull();
    // Empty gap day 11/08/2025 is listed
    expect(screen.getByText("11/08/2025")).not.toBeNull();
  });

  it("merge mode: selecting two trips posts the merge request", async () => {
    mockApi();

    render(<TripsPage />);

    await waitFor(() => {
      expect(screen.getByText("Vacanza in Toscana")).not.toBeNull();
    });

    fireEvent.click(screen.getByRole("button", { name: "Unisci viaggi" }));
    fireEvent.click(screen.getByLabelText("Seleziona Vacanza in Toscana"));
    fireEvent.click(screen.getByLabelText("Seleziona Weekend a Roma"));
    fireEvent.click(screen.getByRole("button", { name: "Unisci 2 viaggi selezionati" }));

    await waitFor(() => {
      const mergeCall = fetchMock.mock.calls.find(([url]) => String(url) === "/api/trips/merge");
      expect(mergeCall).toBeDefined();
      const init = mergeCall?.[1] as RequestInit;
      expect(init.method).toBe("POST");
      expect(JSON.parse(String(init.body))).toEqual({
        tripIds: [1, 2],
        title: undefined,
      });
    });
  });

  it("delete flow: confirms then issues DELETE /api/trips/:id", async () => {
    fetchMock.mockImplementation(async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input);
      if (/^\/api\/trips\/1$/.test(url) && init?.method === "DELETE") {
        return new Response(null, { status: 204 });
      }
      if (/^\/api\/trips\/1(\?|$)/.test(url)) return jsonResponse(TRIP_DETAIL);
      if (/^\/api\/trips\?/.test(url) || url === "/api/trips") return jsonResponse(TRIPS);
      if (url.startsWith("/api/operations")) {
        return jsonResponse({ items: [], page: 1, pageSize: 20, total: 0 });
      }
      throw new Error(`Unhandled fetch: ${url}`);
    });
    render(<TripsPage />);

    await waitFor(() => {
      expect(screen.getByText("Vacanza in Toscana")).not.toBeNull();
    });
    fireEvent.click(screen.getAllByRole("button", { name: "Elimina" })[0]);

    const dialog = screen.getByRole("alertdialog", {
      name: "Conferma eliminazione viaggio",
    });
    expect(dialog).not.toBeNull();

    const before = fetchMock.mock.calls.filter(
      ([url, init]) => String(url) === "/api/trips/1" && (init as RequestInit)?.method === "DELETE",
    ).length;
    expect(before).toBe(0);

    fireEvent.click(screen.getByRole("button", { name: "Sì, elimina viaggio" }));
    await waitFor(() => {
      const del = fetchMock.mock.calls.find(
        ([url, init]) =>
          String(url) === "/api/trips/1" && (init as RequestInit)?.method === "DELETE",
      );
      expect(del).toBeDefined();
    });
  });
});

describe("useAutoDismiss", () => {
  it("clears the message after the delay", async () => {
    function Probe(): React.ReactElement {
      const [msg, setMsg] = useState<string | null>("ciao");
      useAutoDismiss(msg, () => setMsg(null), 30);
      return <p>{msg ?? "(vuoto)"}</p>;
    }

    render(<Probe />);
    expect(screen.getByText("ciao")).not.toBeNull();
    await waitFor(
      () => {
        expect(screen.getByText("(vuoto)")).not.toBeNull();
      },
      { timeout: 2000 },
    );
  });
});

describe("ExclusionZonesPanel", () => {
  const ZONES = {
    items: [
      {
        id: 5,
        scope: "locality",
        locality: {
          id: 7,
          localityHash: "45.56:9.17",
          source: "geoapify",
          countryCode: "IT",
          name: "Milano",
          adminLevel: 8,
          county: "Milano",
          region: "Lombardia",
          country: "Italy",
        },
      },
    ],
  };

  const SEARCH_RESULTS = {
    items: [
      {
        id: 9,
        localityHash: "45.07:7.68",
        source: "geoapify",
        countryCode: "IT",
        name: "Verona",
        adminLevel: 8,
        county: "Verona",
        region: "Veneto",
        country: "Italy",
      },
    ],
  };

  it("lists the configured exclusion zones (§9)", async () => {
    fetchMock.mockImplementation(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.startsWith("/api/exclusion-zones")) return jsonResponse(ZONES);
      throw new Error(`Unhandled fetch: ${url}`);
    });

    render(<ExclusionZonesPanel />);
    await waitFor(() => {
      expect(screen.getByText("Milano")).not.toBeNull();
    });
    expect(screen.getByText(/Lombardia/)).not.toBeNull();
  });

  it("searches a locality and adds it as exclusion zone", async () => {
    fetchMock.mockImplementation(async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input);
      if (
        url.startsWith("/api/exclusion-zones") &&
        (!init || init.method === undefined || init.method === "GET")
      ) {
        return jsonResponse(ZONES);
      }
      if (url.startsWith("/api/exclusion-zones") && init?.method === "POST") {
        return jsonResponse({ id: 6, locality: SEARCH_RESULTS.items[0] });
      }
      if (url.startsWith("/api/localities/search")) return jsonResponse(SEARCH_RESULTS);
      throw new Error(`Unhandled fetch: ${url}`);
    });

    render(<ExclusionZonesPanel />);
    await waitFor(() => {
      expect(screen.getByText("Milano")).not.toBeNull();
    });

    fireEvent.change(screen.getByLabelText("Aggiungi una località da escludere"), {
      target: { value: "Verona" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Cerca" }));

    await waitFor(() => {
      expect(screen.getByText("Verona")).not.toBeNull();
    });

    // The grouped results show one commune row + one province row; the
    // region row appears only when the query matches the region name.
    expect(screen.getAllByText("Comune/località").length).toBe(1);
    expect(screen.getByText("Provincia: Verona")).not.toBeNull();
    expect(screen.queryByText("Regione: Veneto")).toBeNull();

    fireEvent.click(screen.getAllByRole("button", { name: "Escludi" })[0]);

    await waitFor(() => {
      const post = fetchMock.mock.calls.find(
        ([url, init]) =>
          String(url) === "/api/exclusion-zones" &&
          (init as RequestInit)?.method === "POST" &&
          String((init as RequestInit)?.body).includes("9"),
      );
      expect(post).toBeDefined();
      expect(screen.getByText(/Zona di esclusione creata/)).not.toBeNull();
    });
  });

  it("removes an exclusion zone", async () => {
    fetchMock.mockImplementation(async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input);
      if (url === "/api/exclusion-zones/5" && init?.method === "DELETE") {
        return new Response(null, { status: 204 });
      }
      if (url.startsWith("/api/exclusion-zones")) return jsonResponse(ZONES);
      throw new Error(`Unhandled fetch: ${url}`);
    });

    render(<ExclusionZonesPanel />);
    await waitFor(() => {
      expect(screen.getByText("Milano")).not.toBeNull();
    });

    fireEvent.click(screen.getByRole("button", { name: "Rimuovi" }));
    await waitFor(() => {
      const del = fetchMock.mock.calls.find(([url]) => String(url) === "/api/exclusion-zones/5");
      expect(del).toBeDefined();
    });
  });
});
