/**
 * Travelog — TripCard + TripContextMenu tests (new UI, phase 3)
 *
 * Covers the accordion card header (title, period + duration, region tags,
 * photo badge, chevron) and the per-trip gear context menu with its four
 * actions, delegated to the parent callbacks (existing dialogs).
 */

import { describe, it, expect, vi } from "vitest";
import { render, screen, fireEvent, within } from "@testing-library/react";
import type { ComponentProps } from "react";
import TripCard from "../TripCard";
import type { Trip } from "../../api/client";

function makeTrip(overrides: Partial<Trip> = {}): Trip {
  return {
    id: 1,
    name: "Lozon",
    startDate: "2026-07-03",
    endDate: "2026-07-31",
    autoGenerated: true,
    createdManually: false,
    status: "active",
    createdAt: "2026-08-01T10:00:00",
    photoCount: 42,
    regions: ["Valle d'Aosta"],
    ...overrides,
  };
}

function baseProps(
  extra: Partial<ComponentProps<typeof TripCard>> = {},
): ComponentProps<typeof TripCard> {
  return {
    trip: makeTrip(),
    expanded: false,
    onToggle: vi.fn(),
    onRename: vi.fn(),
    onEditDates: vi.fn(),
    onSplit: vi.fn(),
    onDelete: vi.fn(),
    ...extra,
  };
}

const gearFor = (name = "Lozon") => screen.getByRole("button", { name: `Azioni per ${name}` });

describe("TripCard (new UI, phase 3)", () => {
  it("renders the title, period + duration, region tags and photo badge", () => {
    render(<TripCard {...baseProps()} />);

    expect(screen.getByText("Lozon")).toBeTruthy();
    expect(screen.getByText("3 Lug - 31 Lug 2026 · 29 gg")).toBeTruthy();
    expect(screen.getByText("Valle d'Aosta")).toBeTruthy();
    expect(screen.getByText(/42 Foto/)).toBeTruthy();
  });

  it("reflects the expanded state and renders children only when open", () => {
    const onToggle = vi.fn();
    const { rerender } = render(
      <TripCard {...baseProps({ onToggle })} expanded={false}>
        <p>timeline</p>
      </TripCard>,
    );

    const toggle = screen.getByRole("button", { name: /^Lozon/ });
    expect(toggle.getAttribute("aria-expanded")).toBe("false");
    expect(screen.queryByText("timeline")).toBeNull();

    fireEvent.click(toggle);
    expect(onToggle).toHaveBeenCalledTimes(1);

    rerender(
      <TripCard {...baseProps({ onToggle })} expanded>
        <p>timeline</p>
      </TripCard>,
    );
    expect(screen.getByText("timeline")).toBeTruthy();
    expect(screen.getByRole("button", { name: /^Lozon/ }).getAttribute("aria-expanded")).toBe(
      "true",
    );
  });

  it("marks the active card", () => {
    const { container } = render(<TripCard {...baseProps({ active: true })} />);
    expect(container.querySelector(".trip-card--active")).toBeTruthy();
  });

  it("shows a selection checkbox in merge mode and reports toggles", () => {
    const onToggleSelected = vi.fn();
    render(<TripCard {...baseProps({ mergeMode: true, selected: true, onToggleSelected })} />);

    const checkbox = screen.getByRole("checkbox", { name: "Seleziona Lozon" }) as HTMLInputElement;
    expect(checkbox.checked).toBe(true);

    fireEvent.click(checkbox);
    expect(onToggleSelected).toHaveBeenCalledTimes(1);
  });
});

describe("TripContextMenu (per-trip gear, UI §2.1)", () => {
  it("opens the menu with the four actions and calls Rinomina", () => {
    const onRename = vi.fn();
    render(<TripCard {...baseProps({ onRename })} />);

    expect(screen.queryByRole("menu")).toBeNull();

    fireEvent.click(gearFor());
    const menu = screen.getByRole("menu");
    expect(within(menu).getAllByRole("menuitem")).toHaveLength(4);
    expect(
      within(menu)
        .getAllByRole("menuitem")
        .map((item) => item.textContent?.trim()),
    ).toEqual(["Rinomina", "Modifica date", "Dividi viaggio", "Elimina"]);

    fireEvent.click(screen.getByRole("menuitem", { name: /Rinomina/ }));
    expect(onRename).toHaveBeenCalledTimes(1);
    expect(screen.queryByRole("menu")).toBeNull(); // closes after the action
  });

  it("invokes Modifica date, Dividi viaggio and Elimina", () => {
    const onEditDates = vi.fn();
    const onSplit = vi.fn();
    const onDelete = vi.fn();
    render(<TripCard {...baseProps({ onEditDates, onSplit, onDelete })} />);

    fireEvent.click(gearFor());
    fireEvent.click(screen.getByRole("menuitem", { name: /Modifica date/ }));
    expect(onEditDates).toHaveBeenCalledTimes(1);

    fireEvent.click(gearFor());
    fireEvent.click(screen.getByRole("menuitem", { name: /Dividi viaggio/ }));
    expect(onSplit).toHaveBeenCalledTimes(1);

    fireEvent.click(gearFor());
    fireEvent.click(screen.getByRole("menuitem", { name: /Elimina/ }));
    expect(onDelete).toHaveBeenCalledTimes(1);
  });

  it("closes the menu on Escape and on outside click", () => {
    render(<TripCard {...baseProps()} />);

    fireEvent.click(gearFor());
    expect(screen.queryByRole("menu")).toBeTruthy();
    fireEvent.keyDown(document, { key: "Escape" });
    expect(screen.queryByRole("menu")).toBeNull();

    fireEvent.click(gearFor());
    expect(screen.queryByRole("menu")).toBeTruthy();
    fireEvent.mouseDown(document.body);
    expect(screen.queryByRole("menu")).toBeNull();
  });

  it("does not toggle the accordion when opening the context menu", () => {
    const onToggle = vi.fn();
    render(<TripCard {...baseProps({ onToggle })} />);

    fireEvent.click(gearFor());
    expect(onToggle).not.toHaveBeenCalled();
  });
});
