/**
 * Travelog — TripsDashboard (new UI, phase 4) tests
 *
 * Verifies the two-column layout: sidebar with the search field and the
 * accordion trip cards, and the full-height map of the selected trip.
 * Selection is delegated to the parent (`onSelectTrip`) and the card
 * actions reuse the per-trip context menu callbacks.
 *
 * Leaflet is mocked (same approach as trip-map.test.tsx) so only the map
 * mount is observable in jsdom.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, within, waitFor } from "@testing-library/react";
import type { ComponentProps } from "react";
import TripsDashboard from "../TripsDashboard";
import type { Trip, TripDetail, TripMapData } from "../../api/client";

const h = vi.hoisted(() => ({
  state: { mapCount: 0, maps: [] as any[], markers: [] as any[] },
}));

vi.mock("leaflet", () => {
  const state = h.state;

  class MapMock {
    zoom = 8;
    fitBounds = vi.fn();
    flyTo = vi.fn();
    closePopup = vi.fn();
    remove = vi.fn();
    addLayer = vi.fn();
    removeLayer = vi.fn();
    setView = vi.fn(() => this);
    getZoom = () => this.zoom;
    constructor(_el: unknown) {
      void _el;
      state.mapCount += 1;
      state.maps.push(this);
    }
  }

  function makeMarker(latlng: unknown, opts: unknown) {
    const marker: any = {
      latlng,
      opts,
      popupOpen: false,
      handlers: {} as Record<string, () => void>,
      bindPopup: () => marker,
      on(event: string, cb: () => void) {
        marker.handlers[event] = cb;
        return marker;
      },
      openPopup() {
        marker.popupOpen = true;
        return marker;
      },
      closePopup() {
        marker.popupOpen = false;
        return marker;
      },
      getLatLng() {
        return marker.latlng;
      },
      /* Hover visual feedback swaps the icon (TripMap enlarge-on-hover). */
      setIcon(newIcon: unknown) {
        marker.opts = { ...marker.opts, icon: newIcon };
        return marker;
      },
    };
    state.markers.push(marker);
    return marker;
  }

  const chain = () => {
    const obj: any = {
      addTo: () => obj,
      remove: () => {},
      on: () => obj,
      addLayer: () => {},
      clearLayers: () => {},
    };
    return obj;
  };

  return {
    default: {
      map: (_el: unknown) => new MapMock(_el),
      tileLayer: () => chain(),
      layerGroup: () => chain(),
      marker: makeMarker,
      divIcon: (opts: unknown) => opts,
      polyline: () => chain(),
      latLngBounds: (latlngs: unknown) => ({ latlngs }),
      control: { layers: () => chain() },
      Control: class {
        onAdd: (() => HTMLElement) | null = null;
        constructor(_opts: unknown) {
          void _opts;
        }
        addTo() {
          this.onAdd?.();
          return this;
        }
      },
      DomUtil: {
        create: (tag: string, cls: string) => {
          const el = document.createElement(tag);
          el.className = cls;
          return el;
        },
      },
      DomEvent: {
        disableClickPropagation: vi.fn(),
        disableScrollPropagation: vi.fn(),
      },
    },
  };
});

function makeTrip(overrides: Partial<Trip> = {}): Trip {
  return {
    id: 1,
    name: "Lozon",
    startDate: "2026-07-03",
    endDate: "2026-07-31",
    autoGenerated: true,
    createdManually: false,
    status: "active",
    createdAt: "2026-08-01T10:00:00",
    photoCount: 42,
    regions: ["Valle d'Aosta"],
    ...overrides,
  };
}

const TRIPS: Trip[] = [
  makeTrip(),
  makeTrip({
    id: 2,
    name: "Sicilia",
    startDate: "2026-08-01",
    endDate: "2026-08-10",
    photoCount: 7,
    regions: ["Sicilia"],
  }),
];

const MAP_DATA: TripMapData = {
  id: 1,
  name: "Lozon",
  startDate: "2026-07-03",
  endDate: "2026-07-31",
  bounds: { minLat: 0, minLon: 0, maxLat: 1, maxLon: 1 },
  markers: [
    {
      localityId: 10,
      name: "Lozon",
      latitude: 45.7,
      longitude: 7.6,
      photoCount: 5,
      firstPhotoAt: "2026-07-03T10:00:00",
      county: "Aosta",
      region: "Valle d'Aosta",
      country: "Italy",
      countyColor: "#2563EB",
    },
  ],
  countyColors: { Aosta: "#2563EB" },
};

/** Detail of trip 1: one day with the locality 10 (matches MAP_DATA). */
const DETAIL: TripDetail = {
  ...TRIPS[0],
  days: [
    {
      date: "2026-07-03",
      noPhotos: false,
      manual: false,
      localities: [
        {
          localityId: 10,
          name: "Lozon",
          county: "Aosta",
          region: "Valle d'Aosta",
          country: "Italy",
          photoCount: 5,
          manual: false,
        },
      ],
    },
  ],
};

function baseProps(extra: Partial<ComponentProps<typeof TripsDashboard>> = {}) {
  return {
    trips: TRIPS,
    loading: false,
    error: null as string | null,
    selectedTripId: null as number | null,
    onSelectTrip: vi.fn(),
    detailLoading: false,
    detailError: null as string | null,
    mapData: null as TripMapData | null,
    onRename: vi.fn(),
    onEditDates: vi.fn(),
    onSplit: vi.fn(),
    onDelete: vi.fn(),
    ...extra,
  };
}

beforeEach(() => {
  h.state.mapCount = 0;
  h.state.maps = [];
  h.state.markers = [];
});

describe("TripsDashboard (new UI, phase 4)", () => {
  it("renders the sidebar with one card per trip", () => {
    render(<TripsDashboard {...baseProps()} />);

    expect(screen.getByText("I Miei Viaggi")).toBeTruthy();
    expect(screen.getByText("Lozon")).toBeTruthy();
    expect(screen.getAllByText("Sicilia").length).toBeGreaterThan(0);
    expect(screen.getByText("3 Lug - 31 Lug 2026 · 29 gg")).toBeTruthy();
  });

  it("reports the clicked card through onSelectTrip", () => {
    const onSelectTrip = vi.fn();
    render(<TripsDashboard {...baseProps({ onSelectTrip })} />);

    fireEvent.click(screen.getByRole("button", { name: /^Sicilia/ }));
    expect(onSelectTrip).toHaveBeenCalledWith(2);
  });

  it("expands only the selected card and shows the detail loading inside it", () => {
    const { container } = render(
      <TripsDashboard {...baseProps({ selectedTripId: 1, detailLoading: true })} />,
    );

    const first = container.querySelector('[data-trip-id="1"]') as HTMLElement;
    const second = container.querySelector('[data-trip-id="2"]') as HTMLElement;

    expect(within(first).getByRole("status")).toBeTruthy();
    expect(within(second).queryByRole("status")).toBeNull();
    expect(
      within(first)
        .getByRole("button", { name: /^Lozon/ })
        .getAttribute("aria-expanded"),
    ).toBe("true");
    expect(
      within(second)
        .getByRole("button", { name: /^Sicilia/ })
        .getAttribute("aria-expanded"),
    ).toBe("false");
    expect(first.classList.contains("trip-card--active")).toBe(true);
  });

  it("shows the detail error inside the expanded card", () => {
    render(<TripsDashboard {...baseProps({ selectedTripId: 1, detailError: "boom" })} />);
    expect(screen.getByRole("alert").textContent).toContain("boom");
  });

  it("renders the full-height map when the selected trip has map data", () => {
    const { container } = render(
      <TripsDashboard {...baseProps({ selectedTripId: 1, mapData: MAP_DATA })} />,
    );

    expect(h.state.mapCount).toBe(1);
    expect(container.querySelector(".trip-map-container--full")).toBeTruthy();
  });

  it("shows a hint instead of the map when no trip is selected or no map is available", () => {
    const { rerender } = render(<TripsDashboard {...baseProps()} />);
    expect(screen.getByText("Seleziona un viaggio per visualizzarlo sulla mappa.")).toBeTruthy();
    expect(h.state.mapCount).toBe(0);

    rerender(<TripsDashboard {...baseProps({ selectedTripId: 1, mapData: null })} />);
    expect(screen.getByText("Nessuna mappa disponibile per questo viaggio.")).toBeTruthy();
    expect(h.state.mapCount).toBe(0);
  });

  it("routes the card context-menu actions to the matching trip", () => {
    const onRename = vi.fn();
    const onEditDates = vi.fn();
    const onSplit = vi.fn();
    const onDelete = vi.fn();
    render(<TripsDashboard {...baseProps({ onRename, onEditDates, onSplit, onDelete })} />);

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Sicilia" }));
    fireEvent.click(screen.getByRole("menuitem", { name: /Rinomina/ }));
    expect(onRename).toHaveBeenCalledWith(TRIPS[1]);

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Sicilia" }));
    fireEvent.click(screen.getByRole("menuitem", { name: /Modifica date/ }));
    expect(onEditDates).toHaveBeenCalledWith(TRIPS[1]);

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Sicilia" }));
    fireEvent.click(screen.getByRole("menuitem", { name: /Dividi viaggio/ }));
    expect(onSplit).toHaveBeenCalledWith(TRIPS[1]);

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Sicilia" }));
    fireEvent.click(screen.getByRole("menuitem", { name: /Elimina/ }));
    expect(onDelete).toHaveBeenCalledWith(TRIPS[1]);
  });

  it("shows the empty state and the list error", () => {
    const { rerender } = render(<TripsDashboard {...baseProps({ trips: [] })} />);
    expect(screen.getByText("Nessun viaggio trovato.")).toBeTruthy();

    rerender(<TripsDashboard {...baseProps({ error: "Errore di rete" })} />);
    expect(screen.getByRole("alert").textContent).toContain("Errore di rete");
  });

  it("renders the trip timeline inside the expanded card", () => {
    render(<TripsDashboard {...baseProps({ selectedTripId: 1, detail: DETAIL })} />);

    expect(screen.getByText("03/07/2026")).toBeTruthy();
    expect(screen.getByText(/5 foto/)).toBeTruthy();
  });

  it("keeps the timeline and the map in sync (UI §3.1)", () => {
    const { container } = render(
      <TripsDashboard {...baseProps({ selectedTripId: 1, detail: DETAIL, mapData: MAP_DATA })} />,
    );

    const row = () => container.querySelector('[data-locality-id="10"]') as HTMLElement;
    const map = h.state.maps[0];
    const marker = h.state.markers[0];
    const normalIcon = marker.opts.icon;

    // Hovering a timeline row only enlarges the matching pin: no popup and
    // no fly-to (hover must never move the map view).
    fireEvent.mouseEnter(row());
    expect(marker.popupOpen).toBe(false);
    expect(map.flyTo).not.toHaveBeenCalled();
    expect(marker.opts.icon).not.toBe(normalIcon);
    expect(row().classList.contains("locality-card--active")).toBe(true);

    // Leaving the row restores the normal pin and clears the highlight.
    fireEvent.mouseLeave(row());
    expect(marker.opts.icon).toBe(normalIcon);
    expect(row().classList.contains("locality-card--active")).toBe(false);
  });

  it("keeps the search field and the global action menu out of the dashboard (§1.1)", () => {
    render(<TripsDashboard {...baseProps()} />);

    // Both live in the application top bar, rendered by the page.
    expect(screen.queryByLabelText("Cerca viaggi")).toBeNull();
    expect(screen.queryByRole("button", { name: "Nuovo Viaggio" })).toBeNull();
  });

  it("keeps the expanded card read-only without onReplaceDays", () => {
    render(<TripsDashboard {...baseProps({ selectedTripId: 1, detail: DETAIL })} />);

    expect(screen.queryByRole("menuitem", { name: "Modifica viaggio" })).toBeNull();
    expect(screen.queryByRole("button", { name: /Elimina il giorno/ })).toBeNull();
  });

  it("hides the Modifica viaggio entry on archived trips", () => {
    const archivedTrips: Trip[] = [makeTrip({ status: "archived" }), TRIPS[1]];
    render(
      <TripsDashboard
        {...baseProps({
          trips: archivedTrips,
          selectedTripId: 1,
          detail: DETAIL,
          onReplaceDays: vi.fn(),
        })}
      />,
    );

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Lozon" }));
    expect(screen.queryByRole("menuitem", { name: "Modifica viaggio" })).toBeNull();
  });

  it('enables the inline day/locality editing from the "Modifica viaggio" menu voice (§51)', async () => {
    const onReplaceDays = vi.fn().mockResolvedValue(undefined);
    render(<TripsDashboard {...baseProps({ selectedTripId: 1, detail: DETAIL, onReplaceDays })} />);

    // Read-only until the context-menu voice is chosen.
    expect(screen.queryByRole("button", { name: /Elimina la località/ })).toBeNull();

    fireEvent.click(screen.getByRole("button", { name: "Azioni per Lozon" }));
    fireEvent.click(screen.getByRole("menuitem", { name: "Modifica viaggio" }));

    // Deleting the only locality of the day persists the day without it,
    // reporting the trip id to the parent.
    fireEvent.click(
      screen.getByRole("button", { name: "Elimina la località Lozon del giorno 03/07/2026" }),
    );
    await waitFor(() => {
      expect(onReplaceDays).toHaveBeenCalledTimes(1);
    });
    expect(onReplaceDays).toHaveBeenCalledWith(1, [{ date: "2026-07-03" }]);
  });
});
